### ISSUE TITLE
Notification scroll glitch

### ISSUE THREAD

**Issue by Cassolotl** [elk-zone/elk#1001]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I log in. I click the notifications tab, and I have a post with many reblogs and likes.

I scroll a little way, and the column goes mostly blank except for a few reblogs at the bottom.

I scroll back up and the column remains blank.

### Reproduction video or screenshot

https://user-images.githubusercontent.com/6607512/212065147-35a2abc2-0d6a-43b6-a128-38f1bc970e3a.mp4

**Comment by sxzz** [comment]
Try to disable virtual scrolling. 
![image.png](https://volta.s3.fr-par.scw.cloud/image_392a957f7d.png)

**Comment by Cassolotl** [comment]
Thank you, I've just done this and it seems good so far - I'll come back and say something if the glitch happens again.
