### ISSUE TITLE
"Always expand content warnings" and "always show media" settings do not transfer and are not findable

### ISSUE THREAD

**Issue by forestsystem** [elk-zone/elk#1002]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I've never submitted a bug report here before. I copied this format from a couple other issues. Please be gentle if I messed up!

### Clear and concise description of the problem

I have the "Always expand posts marked with content warnings" and "Always show media" settings enabled on disabled.social.

When I logged into Elk, posts marked with content warnings and posts with just media marked as sensitive both stayed hidden, the default setting on Mastodon. I looked for a way to turn these settings back on and could not find it.

### Suggested solution

Make it so these settings transfer into Elk when someone logs in, like how my filters transferred just fine.

### Alternative

Add an easy-to-find way to re-enable these settings after logging into Elk.

### Additional context

If it's relevant, I'm on disabled.social, and I'm using Firefox on desktop. I've also attached a screenshot of one of the posts with a content warning that didn't expand, since the pre-check said to add a screenshot, though I'm not sure how helpful that is in this case.

Thank you for making this client!

### Reproduction video or screenshot

<img width="592" alt="image" src="https://user-images.githubusercontent.com/122533181/212063861-bed9fa69-7aae-4ef3-a326-d899a0b73752.png">

**Comment by ayoayco** [comment]
Thanks for filing the issue! I think this is just a setting we have not implemented on Elk yet. So I will label it as a feature request :)

**Comment by ayoayco** [comment]
@forestsystem Can you attach a screenshot of the settings in mastodon where you set this up to help the dev?

**Comment by forestsystem** [comment]
Here! It's at the bottom of the page on https://[the instance]/settings/preferences/appearance:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/122533181/212194291-4b03df00-106e-4044-8886-8bd1a143f07a.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/122533181/212194315-754653a0-dc3c-47b1-8806-20cd16380c47.png">

**Comment by jasonbrooks** [comment]
It looks like this was fixed in v0.9.4

**Comment by ayoayco** [comment]
Indeed! Does it also apply "always show media" and can we close this? cc @patak-dev

**Comment by patak-dev** [comment]
Easy to support now but not implemented, check https://github.com/elk-zone/elk/commit/16561845f8926366d8998bf33e2d81089b0037b0. PR welcome!

**Comment by ayoayco** [comment]
Looks good, I'll try the other preference.

**Comment by suflors** [comment]
It says this is closed, but it seems it must rely on the instance itself having the setting. I use gotosocial, an instance that doesn't have a frontend itself, so it has no setting for this. Is it possible for there to be a setting on elk itself to automatically open them, regardless of instance settings?
