### ISSUE TITLE
Posts that are bookmarked, do not show immediately  in bookmark page until the page is refreshed

### ISSUE THREAD

**Issue by okoliken** [elk-zone/elk#1003]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I bookmarked a post, I expect it to show up in the bookmark page, on navigating to the page, it does not show the bookmarked item, I had to refresh the page, then the post showed

**Comment by ayoayco** [comment]
Closing this now as I tested now on canary, the bookmarks page shows my bookmarked posts on first load. Please check if you have the latest version and let us know if you encounter it again.
