### ISSUE TITLE
Cannot log into certain instances (tested blorbo.social, fanglitch.space, retro.pizza)

### ISSUE THREAD

**Issue by biasto-bias** [elk-zone/elk#1004]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

Once I managed to open the login prompt, I tried typing in my instance (blorbo.social). It came up with several other instances ending in ".social", but not my instance.

I tested some popular instances (mas.to, c.im, mastodon.social) and they came up fine. Then I tested retro.pizza, aethy.com, and fanglitch.space, and only aethy.com worked.

I've attached a screenshot below of what came up when I typed in blorbo.social.

Thank you!

### Reproduction video or screenshot

<img width="456" alt="image" src="https://user-images.githubusercontent.com/118267931/212069813-9c4d5e05-33ef-40fe-95e3-f243d9edd265.png">

### Additional Context

Browser: Firefox on desktop.

**Comment by danielroe** [comment]
you don't have to select from the dropdown - that's just for ease of use. What happens if you type your instance in full and then click sign in?

**Comment by tom-sherman** [comment]
I can see how the design is confusing. It requires the user to click outside of the input or press enter to dismiss the dropdown list.

I think a super simple fix here is to hide the dropdown when the user enters a valid URL.

**Comment by biasto-bias** [comment]
Thank you so much! I tried clicking outside the dropdown box to make it disappear so I could get to the sign-in button, and it worked fine. I feel pretty silly - sorry about that!
