### ISSUE TITLE
Make theme (light/dark) to follow system preferences 

### ISSUE THREAD

**Issue by Alex0007** [elk-zone/elk#1007]
### Clear and concise description of the problem

I want theme to be changed automatically when my Mac OS theme is changing (sunset/sunrise) instead of manually changing theme every day.

### Suggested solution

Add a "Auto" toggle in theme selector, and implement following system's theme preference

**Comment by tom-sherman** [comment]
Should auto be the default I wonder?

**Comment by tom-sherman** [comment]
Oh, auto is already the default kinda! Cool!

**Comment by Alex0007** [comment]
> Oh, auto is already the default kinda! Cool!

Really? I don't see it in the current stable client build.
