### ISSUE TITLE
Filter and Content Warning logic is wrong

### ISSUE THREAD

**Issue by ayoayco** [elk-zone/elk#1027]
![image](https://user-images.githubusercontent.com/4262489/212163962-83fb8905-7719-474f-b45c-e1000aa0ddcb.jpeg)

In [this post](https://elk.zone/social.ayco.io/@ayo/109677886156981992) I added a content warning text with the word "Twitter". Compare with [mastodon web](https://social.ayco.io/@ayo/109677886156981992)

However I also have a filter for the word "Twitter" so the Status object will have a `filtered` property. 

Couple of things need to be fixed here, but I think could be done together 
- [ ] the author (me) should _not_ be filtered by his filters
- [ ] the content warning should be prioritized over the filter phrase

I think the second one is a regression 🤔

**Comment by boehs** [comment]
Can you test to see if

1. This is also on mastodon official
2. This is still a thing?

**Comment by ayoayco** [comment]
@boehs yes unfortunately this is still a thing 😄 I forgot about this bug, but yeah I confirmed just now. My own posts are being filtered on elk, while not on Mastodon Web.
