### ISSUE TITLE
Translation doesn't work in one very special case

### ISSUE THREAD

**Issue by michelc** [elk-zone/elk#1033]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

When i display this message: https://tantek.com/2023/011/t1/indieweb-evolving-at-mention

If i try to translate it, nothing happens.

But:

* This is a very long message (4000 chars)
* I think @tantek.com@tantek.com is a "special" instance

**Comment by ayoayco** [comment]
As discussed in #1265 this may be solved by ensuring long texts are translated well. Let us track this in that issue, and check this scenario again later. I'll close this for now as duplicate
