### ISSUE TITLE
Default post privacy setting

### ISSUE THREAD

**Issue by tribela** [elk-zone/elk#1040]
### Clear and concise description of the problem

People uses "unlisted/followers" as default posting privacy. But Elk always set posting privacy setting as "public" by default and there is no setting or fetching web settings from server

### Suggested solution

Best solution: Fetch the web setting from home server. and use it as default posting privacy

### Alternative

Second solution: Add a setting to set a default posting privacy for Elk

**Comment by pojntfx** [comment]
Would massively appreciate this as well - this is a bit of a bummer esp. for those using a public and priv account, as I've heard of multiple people accidentally "leaking" their posts publicly because of this already

**Comment by jahtnamas** [comment]
i am an extremely skittish mastodon oldie who doesn't post on public unless i absolutely must, please respect a logged-in account's default post privacy ASAP

**Comment by ayoayco** [comment]
💯 This is a basic mastodon feature that should be supported.

**Comment by mediapinta** [comment]
Please. It's also very important to keep a clean local timeline.
