### ISSUE TITLE
"Show full thread" has incorrect `href`

### ISSUE THREAD

**Issue by MForster** [elk-zone/elk#1059]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

Middle-click or Shift-click on "Show full thread" opens a page "Something went wrong, un(...).v1.statuses.fetch is not a function".

Left-clicking works as intended.

### Reproduction video or screenshot

https://user-images.githubusercontent.com/4067975/212289338-9bee837f-c471-4f19-afc3-d2fcfb9605ff.mp4

### Additional Context

```
entry.dd4eda74.js:9 TypeError: un(...).v1.statuses.fetch is not a function
    at GS (entry.dd4eda74.js:12:73259)
    at middleware (entry.dd4eda74.js:12:75525)
    at s (entry.dd4eda74.js:1:87761)
    at En (entry.dd4eda74.js:1:87790)
    at entry.dd4eda74.js:12:108452
```

**Comment by danielroe** [comment]
This should now be resolved with https://github.com/elk-zone/elk/pull/1121.
