### ISSUE TITLE
Copying the link to a post has an elk.zone domain, or a doubly-wrapped domain

### ISSUE THREAD

**Issue by kevinmarks** [elk-zone/elk#1064]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

This is possibly two bugs:
1. The copy a link on a post gives me the link with elk.zone then my instance then the origin instance. Too much matroshka going on.
2. The link preview in slack (which is calling the elk.zone oEmbed AFAIK) then shows the generic "install elk" preview, not a preview of that post.

**Comment by kevinmarks** [comment]
#2 is a manifestation of https://github.com/elk-zone/elk/issues/153 but it wouldn't happen if the 'copy link' copied the origin link.

**Comment by danielroe** [comment]
I think we can track the social preview in the issue you linked.

Elk offers a permalink solution so when you give someone an Elk URL, it will work for them too, even if they are on a different server. That is why the URL is a bit more complex.

'It's not a bug, it's a feature.'

**Comment by kevinmarks** [comment]
I am used to seeing links prefixed by my own server, but not in the "copy
link" popup. I expect that to be the actual permalink,
***@***.***/109683977996249143
But if I "copy link" I get
***@***.***/109684319592777712

If you want to offer elk cached links, make that a separate menu item there.
 The worst case is if I copy the link from the timestamp and get a
turducken like this
***@***.***@indieweb.social/109684319665788650

I can work around this with a long press on "open in original site" and
copy that url, but I expect "copy link" to do that.

**Comment by kevinmarks** [comment]
I am used to seeing links prefixed by my own server, but not in the "copy link" popup. I expect that to be the actual permalink, https://indieweb.social/@lucasgonze/109683977996249143

But if I "copy link" I get https://elk.zone/indieweb.social/@lucasgonze/109684319592777712
![Screenshot_20230113-231440](https://user-images.githubusercontent.com/99008/212437299-05d48f5c-cb6f-4ea2-8c34-72b7a9ad1fd4.png)


If you want to offer elk cached links, make that a separate menu item there.
 The worst case is if I copy the link from the timestamp and get a turducken like this https://elk.zone/xoxo.zone/@lucasgonze@indieweb.social/109684319665788650
![Screenshot_20230113-231738](https://user-images.githubusercontent.com/99008/212437083-749fc6f0-0d1a-4989-97f5-2ac3aa00e341.png)

I can work around this with a long press on "open in original site" and copy that url, but I expect "copy link" to do that. 
![Screenshot_20230113-231522](https://user-images.githubusercontent.com/99008/212437106-7603a817-9823-45d5-91f8-1754bfcf8d30.png)

**Comment by patak-dev** [comment]
I think we could add a "Copy original link". We eould like for Elk users to be able to get Elk links to share. Let's review how they work once their meta is properly implemented.

**Comment by eamodio** [comment]
I would definitely prefer to copy the original link. Though to be honest, I don't understand what the value an elk.zone link would even provide (even if oembed, etc worked).

**Comment by danielroe** [comment]
> Defaulting to the elk.zone link feels like edging towards "embrace, extend, extinguish" territory. 😬

That's definitely not where we want to be! 🤦 I think @patak-dev's suggestion is good and would be straightforward to implement.

**Comment by forresto** [comment]
elk.zone version of the link didn't unfurl in Discord

![image](https://user-images.githubusercontent.com/395307/213885942-3a376682-fd0a-4b08-a4cb-9e24e3e917b5.png)
