### ISSUE TITLE
Cross for clossing images is almost invisible in white images

### ISSUE THREAD

**Issue by mediapinta** [elk-zone/elk#1067]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [X] I am willing to provide a PR.

### Describe the bug

When adding images to a new publication a cross appears when hovering over the image, but this cross is almost invisible in white images.

### Reproduction video or screenshot

![Screenshot 2023-01-13 at 12-13-23 Elk](https://user-images.githubusercontent.com/13416450/212308875-63d98803-4aa3-4c83-8c5a-9d7a629d9b4f.png)
The cross is almost invisible in this white background screenshot
![elk-screenshot](https://user-images.githubusercontent.com/13416450/212308870-d910eefa-db74-43f1-8597-b3798a7f60e3.png)
Hovering over the cross

### Additional Context

The cross should be visible no matter the colour of the image.

**Comment by forestsystem** [comment]
I thought there wasn't a cross to close it at all - thank you!
