### ISSUE TITLE
Sensitive flag should be ignored if summary == null

### ISSUE THREAD

**Issue by ringtailsoftware** [elk-zone/elk#1072]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

When viewing a post where the `sensitive` flag is `true`, the "show more" prompt should not be shown where `summary == null`.

Here is a post where the `sensitive` flag is `true`, but `summary` is null.

`curl -v -H "Accept: application/activity+json" https://hackers.town/@thegibson/109681977901723288 | jq .`

Elk renders it like this, the "Show more" toggle does nothing:

<img width="639" alt="Screenshot 2023-01-13 at 13 16 03" src="https://user-images.githubusercontent.com/20110944/212329223-f8be1c3e-ca56-48bd-b6ea-db1a0ecdd770.png">

Mastodon renders it like this (ignoring the `sensitive` flag):

<img width="583" alt="Screenshot 2023-01-13 at 13 14 22" src="https://user-images.githubusercontent.com/20110944/212329341-8f634b5c-1916-45e5-9be9-a154684c5dc4.png">

**Comment by ashutosh887** [comment]
I would like to work on this @danielroe @ringtailsoftware

**Comment by ayoayco** [comment]
Hi! Closing this now as PRs #2065 and #2072 will address this, and we will have further improvement on #2068
