### ISSUE TITLE
Keyboard disappeared and wouldn't come back

### ISSUE THREAD

**Issue by forestsystem** [elk-zone/elk#1075]
Another issue I had on the mobile web app (on iPhone): my keyboard disappeared and wouldn't come back. It didn't appear in replies, original posts, or the search bar. I don't know what I did to make it happen. Force-quitting the app (swiping the app up) then reopening it didn't fix it. Waiting several hours (I went to bed) didn't fix it either. I ended up completely restarting my phone, and that fixed it. This is what it looked like:

https://user-images.githubusercontent.com/122533181/212332093-cc11fc3b-f1fd-42e0-b79e-b2df2773a41a.mov

**Comment by boehs** [comment]
It's been 3 weeks. When was the last time this happened to you? I'm inclined to close this because it's so flakey

**Comment by forestsystem** [comment]
I don't think it's happened since I posted this. Maybe someone happened to fix it while fixing something else!
