### ISSUE TITLE
See whether someone has follow requests on

### ISSUE THREAD

**Issue by forestsystem** [elk-zone/elk#1076]
### Clear and concise description of the problem

I would like to be able to see whether someone has follow requests on, so I'm not surprised by requesting to follow someone when I thought I was just following them. Often, people with follow requests on don't want follow requests from strangers. Currently, I'm clicking "open original page" before following someone (partially because of not being able to see their pinned posts - #305).

### Suggested solution

Make the "follow" button say "request to follow" instead, or something similar. (Perhaps "request" to save space, if that's important.) This would be ideal, since it's obvious.

### Alternative

Add a little lock icon somewhere on the person's profile, like how regular Mastodon does it.

### Additional context

Here is what this person's profile looks like on Elk:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/122533181/212333291-b0968d43-47be-45ee-a91a-f0d7869b4e34.png">

Here is what it looks like on Mastodon (note the lock icon):

<img width="564" alt="image" src="https://user-images.githubusercontent.com/122533181/212333309-5fac0491-491a-4951-a4c0-b92c8bc81322.png">

**Comment by ayoayco** [comment]
💯 I think this is another Maston feature that should be supported
