### ISSUE TITLE
edit of toot metadata breaks mentions

### ISSUE THREAD

**Issue by osmaa** [elk-zone/elk#1087]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

1. Post a toot with a mention
2. Edit the toot
3. Do nothing to its content, but change its language
4. Observe that mentions still appear active in editor after ths change
5. Save changes
6. Refresh view
7. Observe that mentions have lost their @ prefix and are no longer highlighted/clickable

### Reproduction video or screenshot

https://user-images.githubusercontent.com/1743200/212371450-1b53aac7-b570-46dd-bf93-9f139c858981.mov

**Comment by edimitchel** [comment]
I think it's something about the popper/tooltip. As you can see the tooltip is still remaining even you focus on the editor again.

**Comment by smallnine9** [comment]
It's an unpleasant bug， I would like to fix it

**Comment by smallnine9** [comment]
And I think it's a bug caused by floating-vue, this issue is related to #1062

**Comment by smallnine9** [comment]
close #1223

**Comment by edimitchel** [comment]
Couldn't reproduce, we could close.
