### ISSUE TITLE
Support italics, etc. from instances that allow it 

### ISSUE THREAD

**Issue by biasto-bias** [elk-zone/elk#1095]
I think it would be nice to see italics, etc. when a user intends their post to be viewed with them. Or at least, the Markdown elements that designate the italics, etc. Currently, it seems that italics just show up as plain text. Links seem to work fine, though.

**Comment by sxzz** [comment]
Elk supported bold and italics now. Could you give some examples that didn't work?

http://localhost:5314/mastodon.world/@hello_world/109683522860150221
<img width="339" alt="image" src="https://user-images.githubusercontent.com/6481596/212401854-2f0459a4-2138-4914-877f-edc3b31aa2cd.png">

**Comment by biasto-bias** [comment]
Here's one (first one Elk, second one the user's home instance):

<img width="582" alt="image" src="https://user-images.githubusercontent.com/118267931/212403516-67ce22ff-a8ca-4d87-ba99-34b9cb7791f8.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/118267931/212403654-e7e9c732-3073-498e-917f-8c515b11baf7.png">

Link: https://aethy.com/@codacon/109683301008517121

**Comment by danielroe** [comment]
let's track in https://github.com/elk-zone/elk/issues/256.
