### ISSUE TITLE
More appropriate placement of `Translate` button.

### ISSUE THREAD

**Issue by Icy-Thought** [elk-zone/elk#1118]
### Clear and concise description of the problem

The translation button is placed in a hidden location at the moment. It also takes two clicks to achieve the desired effect (assuming the translation does not fail, like I'd encountered a couple of times earlier).

### Suggested solution

Create a translation button which appears under the text of the toot only if the user languages does not match the language of the written toot.

Design example:
[ICON](https://www.svgrepo.com/svg/345233/translate) + `Translate toot to X language`. (or without the `X language`)

**Comment by haayman** [comment]
This issue is only partially solved. The link always appears if the language of the toot isn't English, but it doesn't take into account the language of the user

**Comment by alexzhang1030** [comment]
> This issue is only partially solved. The link always appears if the language of the toot isn't English, but it doesn't take into account the language of the user

related: https://github.com/elk-zone/elk/issues/1247

Looks like this is not a BUG. /cc @danielroe

**Comment by haayman** [comment]
I do think it is a bug. Even though it is probably true that most people leave the language of a toot to English/UK, the translate link should appear on every English toot if I set my preferred language to e.g. Dutch. This is not the case. None of the English toots get a translate link, all (most) the Dutch toots do get a link

**Comment by alexzhang1030** [comment]
> I do think it is a bug. Even though it is probably true that most people leave the language of a toot to English/UK, the translate link should appear on every English toot if I set my preferred language to e.g. Dutch. This is not the case. None of the English toots get a translate link, all (most) the Dutch toots do get a link

I will fix it then.

**Comment by alexzhang1030** [comment]
So could you check now this behavour meet your expectations？@haayman

I updated yesterday.

**Comment by haayman** [comment]
In canary?

Op wo 18 jan. 2023 04:26 schreef Alex ***@***.***>:
