### ISSUE TITLE
[Mobile] Local or trending search suggestions?

### ISSUE THREAD

**Issue by Icy-Thought** [elk-zone/elk#1119]
### Clear and concise description of the problem

Clicking on search as of now shows an empty page with a search bar. This, in my opinion, should be the effect noticed by the zen-mode user and not everyone else who has it disabled.

### Suggested solution

Showcase several local search suggestions (or general trending suggestions) for people to read / check when they don't know what they are searching for.

**Comment by boehs** [comment]
Implemented in #1258

**Comment by boehs** [comment]
> for people to read / check when they don't know what they are searching for.

Just wanted to say this reminds me of https://tube.cadence.moe/cant-think
