### ISSUE TITLE
[Mobile] Add Explore (Federated?) to navigation (bottom) bar?

### ISSUE THREAD

**Issue by Icy-Thought** [elk-zone/elk#1120]
### Clear and concise description of the problem

Notifications placement in the navigation (bottom) bar should be occupied by `Explore` or `Federated` page, in my opinion.

### Suggested solution

To counter the lack of space for both notification and conversations, one could combine notifications and conversations into one unified page that is accessible through their individual tab.

**Comment by ayoayco** [comment]
Closing this as we have another issue with customizing the footer nav in mobile. Let's track this here: #641
