### ISSUE TITLE
Grayscale support for digital wellbeing

### ISSUE THREAD

**Issue by ljrk0** [elk-zone/elk#1122]
### Clear and concise description of the problem

Colorful images and UI interfaces encourage interaction, leading to addiction-like behaviors.

### Suggested solution

As part of Elk's digital wellbeing configurations, adding a greyscale or greyscale-optimized mode could tone down the effect of such imagery and interfaces.

### Alternative

Alternatively, some systems such as iOS support a device-wide greyscale mode.  While this is definitely nice to reduce time spent on the phone in general, this filter may work against us by also decreasing contrast of certain UI elements.  Ideally, Elk could detect (how?) that this mode is active and adjust certain UI elements if needed.

However, a system-wide greyscale mode is no replacement for a per-app setting.  Especially on the desktop I need the colors for work but would like to have my social media client to be less distracting.  Also, some systems don't have system-wide greyscale in general.

### Additional context

The now unmaintained client pinafore.social had the option to turn on a greyscale mode (theme) based in recommendations of humantech.com.

Maybe that's something Elk could implement as well, what do you think?

Finally, I just wanted to thank you for the work, I really appreciate all the effort into not "only" developing the most polished client but also caring for r2l languages, digital wellbeing and secure technology (totally hyped about tauri native!).

**Comment by JonasKruckenberg** [comment]
Interesting, do you by any chance have some studies handy or other data to back this up (If it's just something you discovered about your own behaviour that's ofc totally valid too) because it's the first time I heard about this being a strategy to mitigate causes of addiction. I would really like to know more

**Comment by patak-dev** [comment]
Also interested if there are studies to justify this.

We can keep talking here, closing to properly track things now that https://github.com/elk-zone/elk/pull/1177 has been merged. Later on we can create new issues to improve on it.

**Comment by boehs** [comment]
Here is one such study

- https://www.tandfonline.com/doi/abs/10.1080/03623319.2020.1737461?journalCode=ussj20

> In addition, total screen time was significantly less for these individuals by an average of 37.90 min each day. The influence of grayscale did not account for improvement in anxiety or depression

And another, this one a bit broader in scope but publicly accessible https://psyarxiv.com/tjynk

**Comment by ljrk0** [comment]
> Interesting, do you by any chance have some studies handy or other data to back this up (If it's just something you discovered about your own behaviour that's ofc totally valid too) because it's the first time I heard about this being a strategy to mitigate causes of addiction. I would really like to know more

Thanks @boehs for providing actual studies, I had this in Pinafore and subjectively it helped.  Also Apple supports this system-wide so I suppose there's something a bit more substantial to that 0:-)

@patak-dev Now that #1777 is merged, I realize that this issue was (at least) a 2in1.  Shall I create new, separate issues to track grayscale theme & investigation into the iOS-grayscale-mode-detection?

**Comment by patak-dev** [comment]
@ljrk0 yes, please create a new issue linking to these discussions so we can track the feature
