### ISSUE TITLE
Poll result percentage wrong

### ISSUE THREAD

**Issue by MichaelKohler** [elk-zone/elk#1125]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I looked at [this](https://front-end.social/@leaverou/109688267189424003) toot in [Elk](https://elk.zone/front-end.social/@leaverou/109688267189424003) and submitted the poll. This led to the results being shown. The percentage calculation on the graph was wrong though, including "2,400%", "0%", "400%", and "300%" (see screenshot).

### Reproduction video or screenshot

![image](https://user-images.githubusercontent.com/330324/212481861-54048595-360b-4ea7-94ac-ab804b18678e.png)

### Additional Context

Firefox Nightly, Windows 11

**Comment by MichaelKohler** [comment]
After refreshing the page, it now shows all 0%:

![image](https://user-images.githubusercontent.com/330324/212482053-6159e371-04f3-46bc-9fb0-c895f913a5d6.png)

**Comment by Cassolotl** [comment]
I also have this issue! [This poll](https://universeodon.com/@Cassana/109686400189086858) shows like this (0% for everything, 27 votes):

<img width="635" alt="Screenshot 2023-01-15 at 11 14 33" src="https://user-images.githubusercontent.com/6607512/212537499-35acc26a-f67b-48f7-9ca0-8f3e00a7f291.png">

**Comment by danielroe** [comment]
Would you check whether the linked PR solves the issue for you?

**Comment by MichaelKohler** [comment]
Thanks for the fix. Looking good in the deployment preview of your PR, at least for the tweets I linked here. Also couldn't reproduce the wrong initial percentage by voting on a poll either.

**Comment by danielroe** [comment]
The issue was that some polls don't have both votersCount + votesCount, and we were assuming they would.

**Comment by MichaelKohler** [comment]
Out of curiosity, do you know when a poll has both counts and when not?

**Comment by Cassolotl** [comment]
@danielroe 

> Would you check whether the linked PR solves the issue for you?

I don't know how to do that, but I'm happy to wait until the fix has been implemented on elk.zone and then report back!
