### ISSUE TITLE
All / Mention filtering lost for paged notifications

### ISSUE THREAD

**Issue by davatron5000** [elk-zone/elk#1140]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

**I am doing...**

- Go to Notifications view
- Click Mentions tab in that view
- Scroll down to second page of infinite scroll

**What I expect...**

To see only mentions

**What's actually happening...**

I see "All" notifications, not only mentions

### Reproduction video or screenshot

<img width="964" alt="image" src="https://user-images.githubusercontent.com/42218/212497885-b996218b-0f66-4b44-8c9c-b8cba7989738.png">

**Comment by webfansplz** [comment]
Seems `masto.js`'s issue. I created a PR in [masto.js](https://github.com/neet/masto.js/pull/815) and will keep track of it.
