### ISSUE TITLE
Items under ‘Preferences’ could use some descriptions

### ISSUE THREAD

**Issue by ArttuLai** [elk-zone/elk#1142]
### Clear and concise description of the problem

I don't know what the various experimental features under ‘Options’ → ‘Preferences’ do.

### Suggested solution

Add some descriptive text under each of the options so that users know what these features do.

### Additional context

Here's what I‘m referring to:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/42007282/212501210-907c0460-e8c3-4635-9872-65378a2ef164.png">

**Comment by 7glaucio** [comment]
Working on it!

**Comment by ashutosh887** [comment]
I would like to work on this @ArttuLai @7glaucio

**Comment by samuelpath** [comment]
@7glaucio how is this currently going?
