### ISSUE TITLE
[object Object] in page title of followers page

### ISSUE THREAD

**Issue by frostming** [elk-zone/elk#1151]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

Visit the followers page of a user: `https://elk.zone/${server}/@${user}/followers`, and the page title shows: "`关注者 | <user> [object Object]...`"

### Reproduction video or screenshot

![image](https://user-images.githubusercontent.com/16336606/212522459-3d309fa2-c9ee-4957-9570-e3245c6646c6.png)

### Additional Context

Elk version: v0.4.1

**Comment by userquin** [comment]
closed via #1153
