### ISSUE TITLE
Clearer font please!

### ISSUE THREAD

**Issue by Cassolotl** [elk-zone/elk#1170]
### Clear and concise description of the problem

`AI` looks like `Al` on elk.zone:

<img width="617" alt="Screenshot 2023-01-15 at 11 23 36" src="https://user-images.githubusercontent.com/6607512/212537808-7129c4c6-9c36-49f3-ac70-c5f7750187e8.png">

### Suggested solution

New font

### Alternative

Maybe we could have a font where capital-i and lowercase-L don't look identical! :)

### Additional context

Would be super useful for visually impaired users, too.

**Comment by Shinigami92** [comment]
[JetBrains Mono](https://fontsource.org/fonts/jetbrains-mono) is a perfect font to prevent such issues, but it is only available as mono font
I personally do not use JetBrains software like IDEA IntelliJ but VSCode and so I prefer 
[Fira Code](https://fontsource.org/fonts/fira-code)

**JetBrains Mono**:
![image](https://user-images.githubusercontent.com/7195563/212538676-57203355-5147-4b76-9dd7-ddc27ab8c437.png)
**Fira Code**:
![image](https://user-images.githubusercontent.com/7195563/212538687-299cda22-a7cd-4c98-8693-8fe324d2b045.png)

Does someone know a front that's NOT monospace?
We can use these monospace fonts for markdown code blocks

**Comment by ksesong** [comment]
Fira Sans, or rather its extended version [FiraGO](https://github.com/bBoxType/FiraGO), would work well.

[Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans) is also an alternative if we restrict ourselves to typefaces with extended language support.

**Comment by Shinigami92** [comment]
Yes! Lets go with `Fira Code` for mono/code blocks and `FiraGO` for the rest of the UI

**Comment by sxzz** [comment]
Maybe we can add a preference option of custom font, instead of Elk's decision. I pretty much like my OS's built-in font.

**Comment by Shinigami92** [comment]
> Maybe we can add a preference option of custom font, instead of Elk's decision. I pretty much like my OS's built-in font.

Could you open a follow up feature request for that?

**Comment by Cassolotl** [comment]
Yeah, [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans?preview.text=IiLl&preview.text_type=custom) is nice!

<img width="139" alt="Screenshot 2023-01-15 at 16 12 50" src="https://user-images.githubusercontent.com/6607512/212552583-4f5c9534-76cb-4230-b73a-1a99a6f087f5.png">

<img width="480" alt="Screenshot 2023-01-15 at 16 13 17" src="https://user-images.githubusercontent.com/6607512/212552587-c08c570b-8bcb-44f6-8c1c-f6022622509c.png">

**Comment by Shinigami92** [comment]
> Yeah, [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans?preview.text=IiLl&preview.text_type=custom) is nice!

As far as I know Fira (Code/GO/Sans) is a evolution of Noto Sans

IMO we should use Fira because it is a clear and modern font

Check out the examples and screenshots in the PR I submitted right now and feel free to say how you like it

**Comment by ksesong** [comment]
[Fira](https://en.m.wikipedia.org/wiki/Fira_(typeface)) and [Noto](https://en.m.wikipedia.org/wiki/Noto_fonts) are two separate typefaces, different authors, with different objectives. There is no filiation between the two.

It may be worth having one version with Noto, for comparison purposes.

**Comment by Shinigami92** [comment]
> [Fira](https://en.m.wikipedia.org/wiki/Fira_(typeface)) and [Noto](https://en.m.wikipedia.org/wiki/Noto_fonts) are two separate typefaces, different authors, with different objectives. There is no filiation between the two.
> 
> It may be worth having one version with Noto, for comparison purposes.

Maybe you can create such a PR and also in #1179 we can later switch them on demand by user preference

**Comment by antfu** [comment]
As https://github.com/elk-zone/elk/pull/1182#issuecomment-1383224123, let's keep track on https://github.com/elk-zone/elk/issues/1179
