### ISSUE TITLE
Alt text no longer wraps

### ISSUE THREAD

**Issue by snail-coupe** [elk-zone/elk#1181]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [x] I am willing to provide a PR.

### Describe the bug

I was using Elk and viewing a long alt text on a video attachment, all beautifully line wrapped and readable.

 I noticed the "Update Elk" at the top of the page and did so.

Now the same alt text appears on a single line with a horizontal scroll bar which makes it far harder to read 

Could this change be reverted? Or re considered against this and whatever the original issue it was adressing is?

### Reproduction video or screenshot

![Screenshot_2023-01-15-16-01-13-176_com microsoft emmx](https://user-images.githubusercontent.com/53581981/212552163-a78e485c-1e5e-46ac-8f08-c105fe89d17d.jpg)

**Comment by snail-coupe** [comment]
Should have added....
Android 12, Edge 108

**Comment by snail-coupe** [comment]
Reproducible on Window 11, Edge 109

**0.4.1:**
<img width="450" alt="Screenshot_20230115_183854" src="https://user-images.githubusercontent.com/53581981/212560510-a46f412d-6b16-4297-9ae2-9804c1ad0655.png">

**0.5**
<img width="469" alt="Screenshot_20230115_183924" src="https://user-images.githubusercontent.com/53581981/212560540-5019dd83-112f-404c-af35-29761b1de93e.png">

**Comment by snail-coupe** [comment]
Looks like manually removing the whitespace-pre from the <p> fixes this - which appears to revert #1036 
I think using whitespace-pre-wrap (vs white-space-pre) will give the best of both worlds.

**Comment by snail-coupe** [comment]
Manual testing suggests whitespace-pre-wrap works in both cases on my desktop Edge.

**Comment by snail-coupe** [comment]
I've tried to do a fork and a pull request but probably messed something up....

**Comment by patak-dev** [comment]
Fixed by #1193, thanks @snail-coupe!
