### ISSUE TITLE
Configuration of the languages in which the translation button is hidden

### ISSUE THREAD

**Issue by baptiste0928** [elk-zone/elk#1247]
### Clear and concise description of the problem

Actually, the translation button is shown for every toot in a different language than the browser language. We should be able to configure for which languages this button is shown.

### Suggested solution

- [ ] Hide translation button for toots in the same language as the UI.
- [ ] Allow to configure untranslated languages in the settings.
- [ ] Move translate button to the "more" menu for toots where it has been hidden, to translate anyway if needed.

**Comment by edimitchel** [comment]
Actually, your first point is already working but I think people don't use as much the publish language for his post, it's by default English. I open an issue about #1196 to dissociate display language and writing one which is not always the same.

**Comment by edimitchel** [comment]
Your second point could probably fixed by an option in the language preference, also, probably linked with #774 ?

**Comment by Alex0007** [comment]
+1 for additional languages that should not be translated. If i remember correctly, current Mastodon implementation allows to select only 1 language (interface language), while people can know several languages and they don't want to see translate button for them

**Comment by edimitchel** [comment]
There is a publish language preference in mastodon we are planning to use in Elk.
So, publish language should take the precedence over the display if different.

**Comment by Alex0007** [comment]
> There is a publish language preference in mastodon we are planning to use in Elk. So, publish language should take the precedence over the display if different.

I'm using English interface and english language for posts, while i'm native Russian speaker and don't want to translate those posts. With current Mastodon APIs – i can't achieve this

**Comment by edimitchel** [comment]
Good point, so an option of multiple selections of languages correctly understood?

**Comment by niklaswolf** [comment]
I like the idea, too.
Additional to completely disabling translations (see https://github.com/elk-zone/elk/pull/1358) there should be an option to disable translations for n languages from a list of all languages.

I'm willing to work on this feature and provide a PR later on.
