### ISSUE TITLE
Two posts from social.kernel.org renders as empty

### ISSUE THREAD

**Issue by ismail** [elk-zone/elk#1254]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

Open https://elk.zone/@vbabka@social.kernel.org and note that in the most recent thread there are two empty posts.

<img width="794" alt="Screenshot 2023-01-17 at 12 22 17" src="https://user-images.githubusercontent.com/4255/212886840-ba825ea5-9ee4-4873-bedd-a8992038dc01.png">

And here is the Mastodon rendering for the same thread:

<img width="573" alt="Screenshot 2023-01-17 at 12 27 21" src="https://user-images.githubusercontent.com/4255/212887555-331b3d13-694c-4dd0-bdd9-3d47f7058847.png">

**Comment by alexzhang1030** [comment]
Looks like [main](https://main.elk.zone/mas.to/@vbabka@social.kernel.org) branch has been fix this.
