### ISSUE TITLE
Publish to Docker Hub when releasing

### ISSUE THREAD

**Issue by sxzz** [elk-zone/elk#1256]

**Comment by yeahwong** [comment]
I need this too, Thank you.

**Comment by sxzz** [comment]
Closing this. We're using [GitHub packages](https://github.com/elk-zone/elk/pkgs/container/elk) instead.

**Comment by yeahwong** [comment]
> Closing this. We're using [GitHub packages](https://github.com/elk-zone/elk/pkgs/container/elk) instead.

This is no arm64 docker image, could you make a one? Thank you.

**Comment by sxzz** [comment]
Track #2683
