### ISSUE TITLE
Emojis are different in the editor and in the emoji picker

### ISSUE THREAD

**Issue by patak-dev** [elk-zone/elk#1262]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I don't know if this is solvable, but opening an issue to find out if that is the case 

How it looks on Chrome/MacOS

<img width="745" alt="image" src="https://user-images.githubusercontent.com/583075/212922298-5910fd87-2220-47b2-afcb-a859e7dd8ac7.png">

**Comment by alexzhang1030** [comment]
I found that system renders emojis of `emoji-picker`, but actually it is inserted into editor as a picture.

In Windows and Edge

<img width="863" alt="image" src="https://user-images.githubusercontent.com/49969959/212933714-dabc78a9-308f-414a-83a8-dc7d95ebd5d8.png">

**Comment by cyberalien** [comment]
Custom emoji picker that uses emojis available in Elk is in development. It is a complex task, so it will take a while.

**Comment by piotrski** [comment]
@cyberalien we can just switch the emoji set to twitter one [emoji-mart already support it](https://missiveapp.com/open/emoji-mart) 😉

**Comment by cyberalien** [comment]
> @cyberalien we can just switch the emoji set to twitter one [emoji-mart already support it](https://missiveapp.com/open/emoji-mart) 😉

Yes, I think for now it makes sense. Even though emoji set can be configured, it is not trivial to switch yet, so I doubt anyone would change them.

When all emoji stuff will be ready, including configurable sets and emoji picker, it can be switched to new code.
