### ISSUE TITLE
Response doesn't take username into account when calculating the character limit

### ISSUE THREAD

**Issue by billvinson** [elk-zone/elk#1297]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

I typed up a response that contained 497/500, but the reply button didn't "do" anything. Copied my response and tried the typical Mastodon UI & noticed that when I was responding there the same response was 6 characters over the limit. It appears Elk isn't taking the username in consideration when calculating characters used in the response.

The console showed this error which wasn't highlighted in the UI.

MastoHttpUnprocessableEntityError: Validation failed: Text character limit of 500 exceeded

### Reproduction video or screenshot

<img width="599" alt="Screenshot 2023-01-18 at 11 26 51 AM" src="https://user-images.githubusercontent.com/7432642/213236990-6e895e95-0de0-4de6-ba9c-241999414df5.png">

**Comment by webfansplz** [comment]
We've support showing publish failed messages in #1209 (hasn't been released yet).

**Comment by webfansplz** [comment]
Released in V0.6.0
