### ISSUE TITLE
In-app PWA onboarding

### ISSUE THREAD

**Issue by aeharding** [elk-zone/elk#1299]
### Clear and concise description of the problem

Currently, the browser notifies the user that Elk can be installed with an abruptive banner.

The [`beforeinstallprompt`](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent) API (currently Android-only) can let the browser know that the webapp will handle notifying the user. This can lead to less obtrusive patterns to guide the user to install the PWA, for example in-feed:

https://web.dev/promote-install/#in-feed

![image](https://user-images.githubusercontent.com/2166114/213249758-9ed12306-59b3-4821-861e-8cf023f227b5.png)

Or in other places of Elk

### Suggested solution

One of the following:

- A special post is injected into the feed upon receiving a `beforeinstallprompt` event.
- Some other less obtrusive location (ideally a place that regular users would notice, but brand new users wouldn't).

There should be a way to permanently ignore this special call to action.

**Comment by ZMYaro** [comment]
I dislike the suggestion of injecting this into the user's feed (it feels ad-like to me), but perhaps in similar places to where we put the update indicator for installed PWAs, which are less intrusive?

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/213270708-4d0ad60f-07d0-437f-9ad5-e4d7f2abfb60.png)

**Comment by aeharding** [comment]
I've adjusted the issue, because I'm fine with any custom handled solution.

@userquin, how is that handled on mobile? This is where it's most important IMO - it needs to be unobtrusive for brand new Elk users, but noticeable for regular users (have interacted for a while).

This is why I think far down in the feed once every week or so, until the user clicks "ignore" or installs the app, would be ideal: New users aren't annoyed with a banner for an app they don't have experience with, and regular users get a helpful hint (but it's also not an annoying banner or hidden in some obscure menu).

**Comment by ZMYaro** [comment]
@aeharding It shows up as a button in the top bar (when there is room for it, which is most screens).
![image](https://user-images.githubusercontent.com/763405/213276119-f46ca1ca-7a2d-4d39-88a9-7c3c50830619.png)

**Comment by userquin** [comment]
@aeharding for mobile we should show a prompt/toast, we need to allow cancel, there is no space in small devices to include button there

**Comment by userquin** [comment]
rn only shown the install widget, once cancelled not being shown until page refresh

closed via #1451
