### ISSUE TITLE
Tooltip pop up to the right of menu items on small screen

### ISSUE THREAD

**Issue by shuuji3** [elk-zone/elk#1320]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [X] I am willing to provide a PR.

### Describe the bug

1. Tap three dots button
2. Hover on the menu label
3. Tooltip pop up on the right side and the app's layout is broken

### Reproduction video or screenshot

https://user-images.githubusercontent.com/1425259/213477768-163fcd62-bda0-45c6-8c09-6d2da324e08c.mp4

### Additional Context

https://github.com/elk-zone/elk/blob/ae05d3bee5b7e10941bb436d276f90dff0a31804/components/nav/NavSideItem.vue#L56

I guess this `disabled` property is expected to be set to `true` when the screen size is not medium. In other words, the tooltip is expected to be shown only the screen size is medium.

However, the actual definition of `isMediumScreen` is that the screen size is medium or less. So it becomes `false` on the small screen, causing this issue. I'll try to make a PR.

**Comment by jdhartley** [comment]
I came to report this same bug. Happy to help with a PR, let me know if you're already on it.

Looks like we want a `isExactlyMediumScreen`, or _maybe_ some combo of the existing `isMediumScreen` and `isSmallScreen` but that seems hard to grok.
