### ISSUE TITLE
:discord: style emojo auto complete is broken

### ISSUE THREAD

**Issue by wakest** [elk-zone/elk#1322]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

it looks great on the posting interface but the message that gets posted is :undefined::undefined: when it should be :fediverse: :fediverse:  or whatever the emojo code is.

been like this for a few days but just tested on the most recent 'canary' [c200abc](https://github.com/elk-zone/elk/commit/c200abcc900f529cd51356edbd2e3f1bb11bc22a) 

### Reproduction video or screenshot

https://user-images.githubusercontent.com/7890201/213490291-8ff6dddd-e931-443f-8b5d-a6d0babd4991.mov

**Comment by heharkon** [comment]
Came here to report about this, same issue.

**Comment by wakest** [comment]
seemed to be fixed via #1871!
