### ISSUE TITLE
When you edit a post, the page doesn't refresh to show revised post

### ISSUE THREAD

**Issue by supernovae** [elk-zone/elk#1335]
After editing a post and saving it, the old post still shows until you refresh/hit F5.

Saving an edited post should refresh to show the updated post.

Confirmed in 0.6.1

**Comment by rakslice** [comment]
This often leads to problems where earlier edits get reverted because editing starts with some stale version of the post

**Comment by rpavlik** [comment]
Confirmed with 0.7.4, this is visible in a video I recorded for https://github.com/elk-zone/elk/issues/1932
