### ISSUE TITLE
parsing of accounts while logged into Takahē getting split into separate links

### ISSUE THREAD

**Issue by wakest** [elk-zone/elk#1336]
parsing of accounts while logged into Takahē getting split into separate links

link to the post in this screencast https://social.wake.st/users/liaizon/statuses/109718382338430403

link to the account I was testing with https://takiverse.tk/@takiverse@takiverse.tk/

https://user-images.githubusercontent.com/7890201/213583125-9e09bf44-8ec4-43a1-b512-c5ca0e07752f.mov

**Comment by andrewgodwin** [comment]
This is quite possibly an issue on our (Takahē) side, but I've just gone through the JSON generator for `Account` and can't really see any issues. It may be due to slightly different link formats? If it is on our side I can move this problem over there and fix it.

**Comment by wakest** [comment]
@andrewgodwin I am testing out Elk with a few different server backends, it seems like only Takahē shows this behavior so it would make sense that its something you are doing differently maybe. GoToSocial dosen't have this behavior with Elk

**Comment by shuuji3** [comment]
I created an issue in Takahē repository: jointakahe/takahe#479. It seems like the API response from Takahē has duplicated `<a>` tags here.

**Comment by shuuji3** [comment]
We can close this issue as it was solved on Takahė side. 🙂
