### ISSUE TITLE
Move image modal close button to the right corner

### ISSUE THREAD

**Issue by piotrski** [elk-zone/elk#1348]
Can we move the image modal close button to the right corner to prevent overlap with window controls on mac?

![image](https://user-images.githubusercontent.com/244174/213726775-cc80230f-6907-49ea-95a5-91f794563622.png)

**Comment by patak-dev** [comment]
Yes, lets move it 👍🏼

**Comment by Aakarshan-369** [comment]
Hi! I'm a first-time contributor and I worked on this in PR #1381 
Thanks!
