### ISSUE TITLE
Custom tall emojis aren't rendered correctly

### ISSUE THREAD

**Issue by patak-dev** [elk-zone/elk#1350]
https://elk.zone/m.codeflow.club/@stackblitz/109721669842498046

<img width="642" alt="image" src="https://user-images.githubusercontent.com/583075/213744093-7fb2f048-e5f2-4383-82d9-332da0a4cb7a.png">

**Comment by patak-dev** [comment]
This is the emoji
![stackblitz](https://user-images.githubusercontent.com/583075/213744550-bcf3bafb-ae25-4a32-a257-b41a602df934.png)

**Comment by piotrski** [comment]
Haha, they edited out the toot
![Uploading image.png…]()

**Comment by patak-dev** [comment]
> Haha, they edited out the toot

I edited the toot 😅
