### ISSUE TITLE
Layout shift when pressing Follow button on profile

### ISSUE THREAD

**Issue by patak-dev** [elk-zone/elk#1353]
When pressing the follow button, the bell will appear and there is a pixel shift because of it.

**Comment by rkmdCodes** [comment]
Hello I am a new contributor , I am trying to replicate the issue in the dev environment can u please elaborate more on pixel shift . Thanks

**Comment by patak-dev** [comment]
@rkmdCodes press the follow button on a profile of someone you dont follow, you should see the button jumping a pixel down.

**Comment by rkmdCodes** [comment]
I have fixed the issue in this PR #1383 , Please check and thanks

**Comment by patak-dev** [comment]
fixed by https://github.com/elk-zone/elk/pull/1383
