### ISSUE TITLE
Some Special Characters not Viewable in Posts in certain circumstances

### ISSUE THREAD

**Issue by CatelliMstdnCA** [elk-zone/elk#1357]
Posts using <> hide the <> and anything between them.

For example: Posting "I am feeling <fine> today." results in "I am feeling  today." as the post entered on my mstdn.ca account.
If I edit the post, I can see the original.

However: Posting "I am feeling <f@ne> today." results in "I am feeling <f@ne> today." being posted without issue.

Attaching screen shot of this issue as GitHub also does the same thing.

 
![CAPTURE2023-01-20 16_16_32](https://user-images.githubusercontent.com/123210076/213807066-56498d89-f2f0-4462-ac9a-0e76e61e6476.png)

**Comment by boehs** [comment]
Seems to be fixed
