### ISSUE TITLE
Profile hover incorrect

### ISSUE THREAD

**Issue by ChuckByram** [elk-zone/elk#1363]
Love your interface!

I clicked into a post (https://elk.zone/mstdn.social/@mmasnick@mastodon.social/109724122956579017) that had a lot of replies. I noticed that at some point the profile hover became incorrect/out of sync? Seems like it was ok at first, scrolled down a bit, noticed it was wrong, then others that may have been right before weren't anymore? Chrome 109.0.5414.87 on a MBP.

![image](https://user-images.githubusercontent.com/4561211/213845508-455f2738-56a6-498f-9f66-da0c8be287b1.png)

**Comment by bool-kit** [comment]
Fixed by #1964.
