### ISSUE TITLE
Option to turn off media previews 

### ISSUE THREAD

**Issue by fgeierst** [elk-zone/elk#1373]
Twitter has an option to disable media previews in the main timeline
https://www.wikihow.com/Turn-Off-Twitter-Image-Previews , the post detail view still has the image/video. 
This feature is not only useful for data saving, but also may be used to visually calm down the timeline. 
A image url indicates there is an image that you then can see in the detail view.

**Comment by ayoayco** [comment]
Should this also stop the preview cards of links in a post?

**Comment by patak-dev** [comment]
Yes, I think it should @ayoayco. We could have something like the CW filter UI (better a bit lighter, like an icon button, to let users expand and collapse images and expansions (same idea as hovering to recover the colors, it is good to be able to see the full post as others would do without going out of the mode.

**Comment by JohnyTheCarrot** [comment]
@patak-dev Is this still necessary with the data saving mode being a thing now?

**Comment by patak-dev** [comment]
Ya, I think we can close this feature request. Thanks @JohnyTheCarrot!
@fgeierst, check in Settings > Preferences > Enable data saving
