### ISSUE TITLE
[Feature request] Hide boosts from profile feed

### ISSUE THREAD

**Issue by KaKi87** [elk-zone/elk#1378]
Hello,

It would be nice to be able to view posts from a profile excluding boosts.

Related to mastodon/mastodon#21418.

Thanks

**Comment by ZMYaro** [comment]
I think this is a duplicate of #975.

**Comment by patak-dev** [comment]
Thanks @ZMYaro, let's keep the discussion there

**Comment by KaKi87** [comment]
Not exactly, as my idea could have been as simple as a "show boosts" switch but I agree that the other issue is indeed more interesting even if it will probably take more time to implement becaus of complicated decisions.

**Comment by ZMYaro** [comment]
@KaKi87 A couple approaches have been discussed in that ticket, but the core goal is the same—let you view someone's own posts on xer profile, not including boosts.

**Comment by windhamdavid** [comment]
but also hide boost on the home timeline
