### ISSUE TITLE
Remove code block icon from post editor 

### ISSUE THREAD

**Issue by thomykay** [elk-zone/elk#1401]
In favor for simplification for non-tech users elk should remove the code block icon.

Non-tech users will never need it, SW affine users are able to write markdown.

Simplifies, unclutters UI.

![Screenshot_20230123_072031.jpg](https://user-images.githubusercontent.com/33458/213977427-215fbef7-4c01-4f7a-bbb4-8bac9eceb8a7.jpg)

**Comment by patak-dev** [comment]
I think it is a good idea to move these advanced formatting options to a three dots menu in the widget editor. @userquin is working on some other functions that also require we remove some of the always visible options to make place for them.

**Comment by LarsFosdal** [comment]
Just one quick comment - I would not have discovered the Markdown support without that button.
