### ISSUE TITLE
Truncate too long messages

### ISSUE THREAD

**Issue by Geobert** [elk-zone/elk#1425]
Things like this https://main.elk.zone/ligma.pro/@r000t/109745090084127355 take too much space and should be collapsed with a "More…" button maybe?

**Comment by Shinigami92** [comment]
Interesting is that the original is also doing it like this: https://ligma.pro/@r000t/109745090084127355

**Comment by boehs** [comment]
I assume this is because by default posts are limited to 500 chars (and I believe you need a modified server to do this?)

But duplicate of #625
