### ISSUE TITLE
Hide/condense reply count

### ISSUE THREAD

**Issue by gBasil** [elk-zone/elk#1436]
This is a thing Mastodon intentionally does. When a post has more than 1 reply, it displays "1+" instead of the count, with the intention of having people not immediately judge a post on the amount of feedback it received. It would be nice to have a similar option in Elk.
<img width="58" alt="image" src="https://user-images.githubusercontent.com/57513430/214466591-08740d4d-4ff2-41f7-9a55-5e460208af5c.png">

**Comment by boehs** [comment]
I've just added functionality to *hide* reply count. The `1+` is a little different, I'm not sure what's best. Thoughts?

**Comment by boehs** [comment]
> By the way, do you know what the guideline for adding text is? Do you just add it to en.json and let others localize it later?

No clue, I believe so

**Comment by gBasil** [comment]
Could `1+` also be an option? Don't know how the setting for that should be implemented though.
