### ISSUE TITLE
PWA is not fully configured for Android

### ISSUE THREAD

**Issue by josh-collinsworth** [elk-zone/elk#1449]
On Android, if a progressive web app is not fully and properly configured, it can still be installed via a prompt, but it will show as a web shortcut, and will include the icon of the browser that installed it alongside the app icon (rather than just the app icon by itself). It will also not show or be searchable in the list of apps on its own; it will just functionally be a web shortcut in the device's default browser.

I saw a lot of this while installing Wordle-like games last year. Take a look at my home screen; notice how Elk (circled), along with most of the Wordle-like games (slashed through), has the Edge icon along with it.

![Screenshot_20230125-081214~2](https://user-images.githubusercontent.com/22334764/214587317-e89e3ccf-a838-45ea-84ff-094ab47d6276.png)

In some cases that's because the app isn't actually a PWA. For others, it's because it is a PWA but not properly configured. As you can see, Android makes no distinction between the two.

However, the two icons in the lower right (Quina and Hondo, checked) are _also_ both progressive web apps, and neither installs as a shortcut or with the Edge logo, because both of those projects generate the proper files and manifest entries. (They're also both my apps, for full transparency, which is how I know this.)

If I recall correctly, Android expects to find certain manifest entries, and images with a specific name and size, in proper PWA packages. This may help. https://github.com/gokulkrishh/awesome-meta-and-manifest

[Edit: screenshot from a Pixel 4a on Android 13, though I don't thiink device or OS version are relevant in this case.]

**Comment by userquin** [comment]
@josh-collinsworth thx for reporting this, the linked repo is too old: it seems we need to add a maskable icon to the web manifest, latest version of Edge (and LightHouse) complaining, I will check it later...

**Comment by josh-collinsworth** [comment]
Ah, that makes sense. Thanks for following up!

**Comment by userquin** [comment]
@josh-collinsworth PR in a few minutes, I'll need your help to test on Edge Mobile (Android?)

**Comment by josh-collinsworth** [comment]
@userquin You got it.
