### ISSUE TITLE
Remember where you left off

### ISSUE THREAD

**Issue by SoniEx2** [elk-zone/elk#1462]
Currently, elk does nothing to remember where you left off when you close and reopen the browser, despite the browser restoring the session.

However, closing the tab and opening a fresh new one should explicitly forget where you left off.

Proposal: elk should use browser navigation *within* a timeline so that restarting the browser should leave you where you left off, but a fresh tab will have a fresh timeline.

**Comment by boehs** [comment]
duplicate of #653
