### ISSUE TITLE
Render quotes in content distinctly

### ISSUE THREAD

**Issue by johnsonm** [elk-zone/elk#1502]
When rendering quoted content, such as composed on any Fediverse implementation that supports rich text, including but not limited to that composed on the Glitch-soc fork of mastodon, the quoted content should be styled so that it is visibly distinct from non-quoted text. (Note that even the main mastodon supports display of rich text, even though it does not at this time support authoring rich text.)

For example, https://social.makerforums.info/@mcdanlj/109767310773788712 in Mastodon renders like this:
![image](https://user-images.githubusercontent.com/79751/215272321-46b6a74b-2e86-47bd-b895-718ea3d22d97.png)

However, the same post in Elk https://main.elk.zone/social.makerforums.info/@mcdanlj/109767310773788712 does not allow the reader to distinguish quoted and unquoted text:
![image](https://user-images.githubusercontent.com/79751/215272359-b96056da-fd8f-4887-aad0-9d8694446765.png)

Styling quoted text distinctly is important for accurately conveying meaning.

**Comment by danielroe** [comment]
I would also suggest we render markdown blockquotes for situations like this:

```js
Some text here.
> some quoted text
```

**Comment by johnsonm** [comment]
Note that #1509 shows a kind of problem to watch for when doing markdown formatting to an already-formatted posts, though. ☺

**Comment by kvibber** [comment]
Just to add: Misskey and its forks, GoToSocial, and WordPress+ActivityPub are a few other Fediverse platforms that support blockquotes
