### ISSUE TITLE
Implement social images and expansions for elk.zone links

### ISSUE THREAD

**Issue by patak-dev** [elk-zone/elk#153]
Expansion when sharing links on Twitter, Slack, Discord, etc

**Comment by holtwick** [comment]
That would be great. For better context I attached a screenshot of the same Mastodon post shared by using the link from the browser's location field via Apple Messages app. The one from mastodon.social provides a preview.

![20230113-103848-capture-holtwick@2x](https://user-images.githubusercontent.com/49557/212287966-2039a7d7-b41c-4254-9732-a086b03ade23.png)
