### ISSUE TITLE
Custom emoji alignment

### ISSUE THREAD

**Issue by pkmarmor** [elk-zone/elk#1531]
“Short” custom emojis are vertically misaligned in Elk. @Pedantic commented on Discord “It seems like the  `vertical-align: text-bottom;` is causing it. On the `.custom-emoji` class.”  See attached screenshot.

![D41EC952-DBC7-4B21-B02E-6D126DCA8B7D](https://user-images.githubusercontent.com/11763465/215657752-2ce49ac9-12a4-46e5-954f-ba435288b850.jpeg)

**Comment by shuuji3** [comment]
It looks like this issue was solved with #2007. 🙂
