### ISSUE TITLE
Ampersand characters in post content are being incorrectly escaped

### ISSUE THREAD

**Issue by msfjarvis** [elk-zone/elk#1536]
On version [`611b6bece70bb53c2ee73d4777d02d35c4734653`](https://github.com/elk-zone/elk/commit/611b6bece70bb53c2ee73d4777d02d35c4734653) of Elk Canary (https://main.elk.zone), I can reproduce an issue where `&` characters are being incorrectly URL-encoded.

1. Toot URL: https://toot.yosh.is/@yosh/109783568066855672
  - Real URL: `https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0bea004ce462edbb6cfb854c285fec71`
  - Elk's version: `https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2021&amp;gist=0bea004ce462edbb6cfb854c285fec71`

2. Toot URL: https://androiddev.social/@msfjarvis/109783701615496821

<details>
<summary>Toot shown on Mastodon</summary>

![image](https://user-images.githubusercontent.com/13348378/215756818-471f81c1-e784-41a4-99af-2696b7eb5871.png)

</details>

<details>
<summary>Toot shown on Elk</summary>

![image](https://user-images.githubusercontent.com/13348378/215756995-99edad1b-8e46-460d-a7c2-39fa3cbdb117.png)

</details>

**Comment by simonw** [comment]
I just ran into that bug here as well: https://elk.zone/fedi.simonwillison.net/@simon/110155245432996578
