### ISSUE TITLE
Possibility to edit the entire reply (e.g. deletion of the initially mentioned user)

### ISSUE THREAD

**Issue by dnlsch** [elk-zone/elk#1547]
When I reply to a toot, the author's handle is set automatically. On the one hand, this is a nice feature so I can focus on replying. On the other hand, sometimes I would like to edit the entire toot. For example, if I want to reply in the @Direct-mode, but only want to mention a friend and not the author of the toot.

I think it would be an enhancement if one had the possibility to edit the entire toot. For exmaple a button that shows the source text of the toot.

**Comment by johnsonm** [comment]
You can click on any of the names that have been set automatically to remove them from the list.

**Comment by dnlsch** [comment]
> You can click on any of the names that have been set automatically to remove them from the list.

Oh...that was not obvious to me, thx!

**Comment by ZMYaro** [comment]
It may make sense to consider making the names check-/uncheckable.  Maybe not a whole dialog like Twitter, but at least making the names more clearly selectable where they are right now?
