### ISSUE TITLE
UX: Improve user's path to explore on mobile

### ISSUE THREAD

**Issue by ronilaukkarinen** [elk-zone/elk#1560]
Right now I always press search, because default Mastodon interface has Search + Explore combined. Because of this I always end up pressing search (as it's sticky on the bottom nav) and end up on this empty view:

<img src="https://user-images.githubusercontent.com/1534150/216104905-9277347d-4459-4f18-b12b-9396643a8236.png" width="420">

In my opinion the current search feature on Mastodon is rarely used. The views are actually great as combined, because the search occupies very little space. 

Suggestion 1:
Combine these views.

Suggestion 2:
Add explore icon on bottom to the mobile in place of search.

**Comment by ZMYaro** [comment]
There is already a proposal to combine them, somewhat like Twitter—#1274.
