### ISSUE TITLE
Web share target misconfiguration

### ISSUE THREAD

**Issue by TheWebTech** [elk-zone/elk#1565]
I've noticed that for some reason the URL isn't received from the web share API when you select Elk as a share target. Or at least it doesn't fill the URL into the text box.

It does appear to get the text.

To reproduce:
* install elk as a pwa
* go here https://web-share.glitch.me/ click share and choose elk. URL will be left off.

Not entirely sure where the web manifest file is in this project but that could be the culprit.
https://developer.chrome.com/articles/web-share-target/

Otherwise my second theory is that we're just not checking for the URL param and passing it to the text field.

**Comment by userquin** [comment]
@TheWebTech yes, the url is not handled, the manifest can be found here: https://github.com/elk-zone/elk/blob/main/modules/pwa/i18n.ts#L106 and share target here https://github.com/elk-zone/elk/blob/main/service-worker/share-target.ts#L50

The client can be found here https://github.com/elk-zone/elk/blob/main/components/publish/PublishWidget.vue#L108 and composable here https://github.com/elk-zone/elk/blob/main/composables/web-share-target.ts ()

**Comment by userquin** [comment]
@TheWebTech it seems Android not supporting url, check this entry https://developer.chrome.com/articles/web-share-target/#verifying-shared-content

**Comment by horvbalint** [comment]
I might not understand the problem correctly, but if I share an URL with Elk, it opens and the link is placed inside the text area as I would expect.

**Comment by horvbalint** [comment]
@TheWebTech @userquin
I see the problem, when I created the manifest I merged the 'text' and 'url' options into one, because we handle them the same way. But this means that if both are shared in the same time, then the 'url' is overwritten by the 'text'.
For me it worked because I shared from the url-bar and that way only the url was shared with Elk.

I will fix it after work :)

**Comment by userquin** [comment]
Fixed via #1572
