### ISSUE TITLE
Will elk support nostr?

### ISSUE THREAD

**Issue by wey-gu** [elk-zone/elk#1566]
I know this sounds silly as elk is for Mastodon, but, look at the [nostr web clients](https://nostr.com/) out there:

<img width="336" alt="Screenshot 2023-02-02 at 10 05 50" src="https://user-images.githubusercontent.com/1651790/216213330-c86a5f17-ba38-4c5a-a27d-6540f4a2fdc3.png">

:D
update: looks like https://iris.to/ is not that bad.

**Comment by gBasil** [comment]
Although this doesn't definitively answer your question, I think Elk is more geared towards software that implements the ActivityPub protocol. As of now, you could theoretically use Elk with Nostr with something that allows the two to interact with each other, but I don't think anything for that exists.

**Comment by boehs** [comment]
Agreed with @gBasil. We still have so much ideas with Mastodon and ActivityPub, it's just not feasible to support an API so different from Mastodon. You're welcome to fork elk, or enhance the existing clients with a better UI.

**Comment by melvincarvalho** [comment]
There is another way that is compliant with ActivityPub

I made this vocab, if you can add the following predicate to your profile:

https://w3id.org/user#nostr

Then elk users can add their nostr pubkey and use both systems.  It would mean adding a line to the JSON profile, if that's indeed possible.

There's tons of client side apps for nostr now, so it would be a nice bridge to the fediverse
