### ISSUE TITLE
Sidebar location should behave as defined by the Interface language setting in Appearance

### ISSUE THREAD

**Issue by hanan-cohen** [elk-zone/elk#1569]
My Interface language setting in Appearance is English.

Currently, the sidebar moves to the right if the post language is defined as Hebrew. When reading an English post, it moves to the left. This is an annoying behavior.

Test using this post

https://elk.zone/tooot.im/@hananc/109794194639061904

See screenshot
![2023-02-02 11_50_38-Settings](https://user-images.githubusercontent.com/15553877/216292852-244d63e6-44cf-40fb-9bd3-e7b9e8bae43b.png)

**Comment by boehs** [comment]
oh lord this is terrible
