### ISSUE TITLE
Cannot enable notifications in Brave browser

### ISSUE THREAD

**Issue by IanVS** [elk-zone/elk#1574]
I tried to enable desktop notifications but got an error:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/4616705/216408166-15f21843-2271-46d3-9a86-838520aae95e.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/4616705/216408578-ca9521f2-4c84-4efe-a822-31af78e8818a.png">

It would also be nice to give the link to the repo, so users don't have to search for it.

**Comment by tonilampela** [comment]
Same issue with Orion browser.

**Comment by userquin** [comment]
I'll provide the message in the console in the error dialog and repo link.

**Comment by userquin** [comment]
@IanVS like this one (I will add an icon for external link)?

![imagen](https://user-images.githubusercontent.com/6311119/216713649-13f38dfd-07ab-4e75-838b-e0529570a4ad.png)

**Comment by IanVS** [comment]
Nice, yeah I think that's much better!  Thanks!

**Comment by IanVS** [comment]
I think that the referenced PR is a good step, but I don't think it closes this issue.  The situation remains that notifications cannot be enabled.
