### ISSUE TITLE
Elk PWA on main.elk.zone does not refresh on Firefox on Android

### ISSUE THREAD

**Issue by johnsonm** [elk-zone/elk#1584]
I have installed main.elk.zone as a PWA on Firefox on my Android device running Android 13.

Within the last few days, it has almost entirely stopped refreshing. Tapping the Elk icon (only visible in landscape mode) does not refresh, and it only refreshes a few times per day. I don't know exactly what triggers it to be able to update. The only thing I can do to refresh it is to stop the entire Firefox app and then start it again. Otherwise, it has picked up newer content only a few times; I'm seeing only hours-old content even though the web view and Tusky both see current content.

**Comment by userquin** [comment]
maybe related to this https://github.com/elk-zone/elk/issues/750?

**Comment by boehs** [comment]
> maybe related to this #750?

Merge?

**Comment by userquin** [comment]
@johnsonm see video here https://github.com/elk-zone/elk/pull/1658#issuecomment-1419691657

**Comment by johnsonm** [comment]
While this completely fails less often, I still end up in this state when switching between wifi and data, and clicking the Elk logo still doesn't refresh. Elk is still unusable as a PWA as a result, so I've had to revert to using it only in a browser tab where I have access to the browser refresh feature.

This has been consistent since #1658 was resolved, so there's more to it than just that.
