### ISSUE TITLE
Make images in preview zoomable via pinch zoom

### ISSUE THREAD

**Issue by Shinigami92** [elk-zone/elk#1595]
On mobile/pwa it is sometimes hard to read content in an image
It should be possible to zoom the image via pinch zoom
The content in background should not be affected by that

**Comment by sarajw** [comment]
Thanks for writing the issue, I find this a big problem for mobile use!

**Comment by purcell** [comment]
Yes! It's super common to click on an image on mobile devices and then want to zoom and pan around, either to see details or read small text. The inability to do this has really been the only jarring thing I've encountered when using Elk.
