### ISSUE TITLE
HTTP 500 error on main.elk.zone

### ISSUE THREAD

**Issue by lenke182** [elk-zone/elk#1626]
Opening https://main.elk.zone/ replaces the URL with https://main.elk.zone/m.webtoo.ls/public/local

However directly opening https://main.elk.zone/m.webtoo.ls/public/local produces a HTTP 500 error.

**Comment by userquin** [comment]
closes via https://github.com/elk-zone/elk/commit/e31fc4087c0aa66917106a4ab00238de980e7d1c
