### ISSUE TITLE
Missing dependencies cause build to fail when using NITRO_PRESET=cloudflare

### ISSUE THREAD

**Issue by DataDrivenMD** [elk-zone/elk#1630]
## Issue:
Build fails at the prerender step when `NITRO_PRESET=cloudflare`. Adding the requested dependencies snowballs into a missing peer-dependency nightmare. Even after all the dependencies are satisfied, the build fails due to a missing export in a third-party module (the sparkline charting library).

## Expected:
As with `NITRO_PRESET=netlify` the app should prerender successfully when `NITRO_PRESET=cloudflare`

## Steps to reproduce:

1. Start with a clean slate: `rm -rf .nuxt && rm -rf .netlify && rm -rf dist && rm -rf node_modules && rm -rf .output`
2. Install build dependencies: `pnpm --filter=\!./docs i --frozen-lockfile` -- Note that the filter argument is necessary due to dependency conflicts caused by a subproject in the `/docs` folder -- might want to consider moving documentation into its own repo
3. 

```NODE_ENV=production HOST=0.0.0.0 \
NUXT_PUBLIC_DEFAULT_SERVER=fedified.com \
NUXT_CLOUDFLARE_ACCOUNT_ID=<NUXT_CLOUDFLARE_ACCOUNT_ID> \
NUXT_CLOUDFLARE_NAMESPACE_ID=<NUXT_CLOUDFLARE_NAMESPACE_ID> \
NUXT_CLOUDFLARE_API_TOKEN=<NUXT_CLOUDFLARE_API_TOKEN> \
NUXT_STORAGE_DRIVER=cloudflare
PORT=5314 \
NITRO_PRESET=cloudflare nuxi build```

**Comment by danielroe** [comment]
At this point the build should be succeeding - since https://github.com/elk-zone/elk/pull/1647. There is still one more issue with cloudflare, see https://github.com/unjs/nitro/issues/787.
