### ISSUE TITLE
Have an icon only sidebar mode

### ISSUE THREAD

**Issue by nikitavoloboev** [elk-zone/elk#1642]
Coming to Elk from Twitter, I find scrolling through the feed distracting as there is too much text to the left side.

Elk:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/6391776/216841836-69809d50-354f-43c1-ad7a-bfd5c0f066f7.png">

Twitter:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/6391776/216841881-c5842da8-fe7b-4cbe-99d7-eb19cc0c2692.png">

I want to get my Elk experience to be identical to Twitter's. So only icons visible on the side. Also hide this:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/6391776/216841901-b4ce3f78-d3d8-40a1-a754-83c8ab151b0f.png">

I can do it potentially via a third party extension on top but would love to avoid doing this. An optional setting for `icons only` would be perfect.

Thank you.

**Comment by boehs** [comment]
Making the window smaller collapses the icons. Clicking the button next to the moon hides everything for a zen experience!

**Comment by nikitavoloboev** [comment]
That's nice. I would still love for same zen experience without having to zoom in.

**Comment by boehs** [comment]
As I said, clicking the icon in the bottom right next to the moon hides the UI

**Comment by nikitavoloboev** [comment]
Ohh my bad, I misread it. Ok perfect then.

Is it possible to activate zen mode from keyboard? By pressing `z` key perhaps? Or should I open a new issue for this?

**Comment by boehs** [comment]
#39 #319
