### ISSUE TITLE
Elk counts full characters lenght from links

### ISSUE THREAD

**Issue by mediapinta** [elk-zone/elk#1651]
A link/url address in Mastodon web is always 23 characters long, not matters the lenght. Elk counts all the characters from links for character count maximum.

I think Elk should match Mastodon web behaviour (or similar).

![imagem](https://user-images.githubusercontent.com/13416450/216940384-b7cb1af7-194c-4c71-b2f6-11edafb3a963.png)
A 111 characters long link in Elk.
![imagem](https://user-images.githubusercontent.com/13416450/216940543-a85d3450-c2da-4718-a178-cc8c3ac15ca2.png)
A 111 characters long link in Mastodon web.

**Comment by 4350pChris** [comment]
@mediapinta I have opened a PR for this and would appreciate feedback.
