### ISSUE TITLE
Search description sits on top of other nav buttons on mobile

### ISSUE THREAD

**Issue by joaosamouco** [elk-zone/elk#1657]
I think the current UX could be improved. When navigating to the Search/Explore page, the search input is automatically focused, which I think is good, but the search input description text (_"Search for people & hashtags"_) sits on top of the navigation links, and on mobile is not that easy to dismiss it. If a user doesn't want to search for anything specific and goes to the Explore page to do just that, "explore", it isn't the best experience.

![search screen on mobile](https://user-images.githubusercontent.com/6799006/216992050-718d166d-22e1-4920-8fb9-948ae4e22ca1.png)

https://user-images.githubusercontent.com/6799006/216993622-be6ea9f4-5fb6-4f86-b51d-b2d2b8c5fe7b.mp4

**Comment by shuuji3** [comment]
Currently, the "Search" and "Explorer" tabs are separated as independent, so this issue is solved. We may reorganize the search page in the future and will keep this UI issue in mind at that time. Thanks for reporting!
