### ISSUE TITLE
Switch between lists using a tab bar (or similar) on the home screen

### ISSUE THREAD

**Issue by dnlsch** [elk-zone/elk#1677]
Opening a certain list is pretty unintuitive in the current version. It would be nice to have the option to activate a kind of tab bar on the home screen that shows your lists, so you can switch with one click. This is exactly how it is implemented in the Fedilab client.

**Comment by raphmim** [comment]
+1 on this!

**Comment by patak-dev** [comment]
I think there were already some discussions about the UI around this... ok, found it. @dnlsch @raphmim let's discuss how the UI should look on this issue:
- https://github.com/elk-zone/elk/issues/1540

Closing as duplicate, please comment there if you think that the idea in the issue wouldn't be enough.
