### ISSUE TITLE
Add Matrix and email profile metadata icons

### ISSUE THREAD

**Issue by salarua** [elk-zone/elk#1683]

**Comment by ZMYaro** [comment]
Elk uses the [Remix icon pack](https://remixicon.com).  I am not sure which icon from that, if any, would make sense for Matrix, but email should definitely be doable!

**Comment by salarua** [comment]
there doesn't seem to be a Matrix icon at all. it wouldn't be difficult to make though since it's literally just a lowercase m in square brackets: [m]

**Comment by ZMYaro** [comment]
@salarua I just checked, and it appears someone already submitted a request for one! https://github.com/Remix-Design/RemixIcon/issues/209

**Comment by salarua** [comment]
I noticed today that Matrix now has an icon. Thank you!
