### ISSUE TITLE
Character count is incorrect when links are present

### ISSUE THREAD

**Issue by maxcalvin** [elk-zone/elk#1688]
In the compose component on elk, adding a link or url is counted as individual characters for the remaining characters count.

However, urls in posts use a shortener (or something?) and therefore take up a constant number of chars in the post, no matter the length of the input url. I don't know if the character count varies based on instance, but on hachyderm.io, a url counts as 23 chars, even if shorter or longer. 

Ideally the compose box should recognise any urls and ignore their character count, instead adding the constant value. Having the incorrect character count makes it hard to know when the post is valid to send or not.

Thanks!

**Comment by Mini-ghost** [comment]
It seems to be related to this issue: <https://github.com/elk-zone/elk/issues/1651>, and it is fixed by <https://github.com/elk-zone/elk/pull/1660>.
