### ISSUE TITLE
Docker image doesn't allow signup to Fediverse instance

### ISSUE THREAD

**Issue by maxheadroom** [elk-zone/elk#1696]
Looks like the last change on the Dockerfile (Commit 331f517d758b477075a42b9b30660cb6670111fe) introduced running the service as non-root user. The result seems to be, that one can't sign in to any server anymore. When trying to sign in one only get's an error message that the service can't connect to the server.

With the default settings, there is no error message in the output of nodejs in the container. Even with ```DEBUG="*"``` set there is no error message or other information in the output of nodejs why the service can't connect to the fediverse instance.

If one removes the ```USER elk``` from the Dockerfile and re-creates the Docker image, it works just fine.

**Comment by kkoyung** [comment]
I had this problem before. I guess it is due to the permission of persistent storage.

In the `Dockerfile`, it declares a persistent storage `/elk/storage`. When you create a contain without mounting volume for that directory, docker will automatically create an unnamed volume for it. By default, the unnamed volume created by docker is owned by root. However, the `Dockerfile` also set the default user to be UID 1000 and GID 1000. Therefore, that user cannot write file to /elk/storage.

To make it work, you have to mount a volume to /elk/storage which allow user with UID 1000 to write.

**Comment by maxheadroom** [comment]
I'll give that a try and and update the docker-compose.yaml accordingly if it works.

**Comment by b2cc** [comment]
@maxheadroom : just checked with latest `main` on Openshift, and the login error still persists for me on Openshift. Does it work for you on native docker now?

**Comment by maxheadroom** [comment]
Yes, it works on native Docker for me. The PR that was merged here are basically the changes I had to make to the docker-compose.yml file to fix the issue for me.

**Comment by b2cc** [comment]
Ok, just solved this  - was a weird routing issue on my end. For anyone stumbling across this, maybe this will help them, so I'm putting this out here.

My setup looks pretty much as in this comment: https://github.com/cert-manager/cert-manager/issues/2517#issuecomment-889961035 , and I ran into the same issue described there. Basically I have a router/gateway with a 1:1 NAT in front of the Mastodon and Elk apps. The Elk app runs in a private IP namespace (think 10.1.x.y.), next to Mastodon, both behind the Router.

What happened for me was that the Elk app was hitting the "internal" interface of the firewall when it tried to connect to Mastodon during the "Login" process, and the request was not routed correctly back to Mastodon, triggering this weird "Cannot connect to the server" error message, which was technically correct, but didn't tell me anything at that point.

To resolve this issue I just added a host alias to the deployment which points to the internal IP of the kubernetes/Openshift ingress where mastodon is running.

deployment.yaml, abbreviated
replace `10.1.x.y` with the internal IP of the ingress and `mastodon.example.com` with the domain name of the mastodon instance.
```
spec:
  template:
    spec:
      name: mastodon-elk
      hostAliases:
      - hostnames:
        - mastodon.example.com
        ip: 10.1.x.y
```

**Comment by shleeable** [comment]
That's fine if I want to limit elk users to only my instance?

**Comment by maxheadroom** [comment]
I think this issue is resolved with the updated documentation to clarify that there isn't a bug but just a permission error storing the configs.

**Comment by shleeable** [comment]
https://github.com/elk-zone/elk/issues/1739#issuecomment-1958828717
