### ISSUE TITLE
Automatic theme switch based of OS theme

### ISSUE THREAD

**Issue by nikitavoloboev** [elk-zone/elk#1703]
Didn't see it as an option in UI and also in issues. Perhaps it's already implemented or has been asked for. 

I change OS color theme often if I work outside/inside so it would be very useful for me.

**Comment by ZMYaro** [comment]
This is an option, under Settings → Interface:
![Screenshot_20230210-120029](https://user-images.githubusercontent.com/763405/218151797-3491026e-fa9c-4cd6-9699-97dc9ada2b59.png)

**Comment by nikitavoloboev** [comment]
Oh nice. 

Maybe here:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/6391776/218152310-0c766352-d134-4ca3-933d-f2b2edc536f2.png">

When you press it will toggle between light/dark and also automatic themes?
