### ISSUE TITLE
Show user card when hovering over tagged (profiles) links.

### ISSUE THREAD

**Issue by santiagofn** [elk-zone/elk#1718]
User cards are shown when the cursor hovers over a profile photo

![image](https://user-images.githubusercontent.com/8375708/218272874-28d7a5a4-0538-4f19-bea3-7a5bdaae9451.png)

But not when it hovers over a tagged link:

![image](https://user-images.githubusercontent.com/8375708/218272922-66367316-db84-4013-b8fd-6db997b9892b.png)

My proposal is to add this last behavior, just like Twitter web does:

![image](https://user-images.githubusercontent.com/8375708/218272765-b2a5349a-2a92-4e6a-8385-bc3d4ef39950.png)

**Comment by raphmim** [comment]
+1 on this. Displaying user cards when hovering over profile photos create the subconscious expectation that we'll get the same when hovering over tagged profiles links, so when it doesn't happen it's quite confusing.
