### ISSUE TITLE
Translation sometimes take a while (on first request)

### ISSUE THREAD

**Issue by Shinigami92** [elk-zone/elk#172]
The first request of a text does take a while

This is okay, but we should show a loading indicator to indicate that something is happening in the background

https://user-images.githubusercontent.com/7195563/204136146-bd201152-dcb5-4ad4-b811-6cd01ad89c47.mp4

#UX

**Comment by alexzhang1030** [comment]
I thinks it's been resolved now. /cc @danielroe WDYT?
