### ISSUE TITLE
`GET https://aus.social/api/v1/push/subscription` 404

### ISSUE THREAD

**Issue by shleeable** [elk-zone/elk#1737]
![image](https://user-images.githubusercontent.com/17537000/218356882-0c54d361-6284-4dd5-996a-d398bbf4c17b.png)

This happens every time on a logged in user on my Mastodon 4.1.0 instance.

**Comment by userquin** [comment]
@shleeable this is by design (mastodon api): the backend will return 404 when there is no push subscription, Elk send the request when signing-in to your server:

https://docs.joinmastodon.org/methods/push/#404-not-found
