### ISSUE TITLE
Console error `DOMException: A mutation operation was attempted on a database that did not allow mutations.` on logged out user

### ISSUE THREAD

**Issue by shleeable** [elk-zone/elk#1738]
![image](https://user-images.githubusercontent.com/17537000/218357180-c6dd2d1c-7a5f-4ff9-9e1e-f63fe8cb562f.png)

This error doesn't show up on my logged in user.

**Comment by userquin** [comment]
Dont use it in private browsing, IIRC Firefox has this bug still open (13 years)
