### ISSUE TITLE
cannot connect to `aus.social` from `https://elk.aus.social/` after upgrade from mastodon 4.0 to 4.1 / elk 0.7.2 to 0.7.4

### ISSUE THREAD

**Issue by shleeable** [elk-zone/elk#1739]
Issue: New logins are failing on latest Mastodon/ELK. Old sessions seem fine. new ones are unable to connect.

I upgraded both Mastodon/ELK. I didn't touch the nginx conf.

![image](https://user-images.githubusercontent.com/17537000/218357771-06cfaff0-2cc9-44c8-9728-b5a31260e017.png)
![image](https://user-images.githubusercontent.com/17537000/218357790-be0c0548-8c2b-4c76-9e13-cab7f56ddf33.png)
![image](https://user-images.githubusercontent.com/17537000/218357804-7435e547-bcbe-4e6f-a596-670d120690a2.png)

**Comment by shleeable** [comment]
Downgrade to v0.7.2 worked. Regression?

**Comment by b2cc** [comment]
This seems to be the same issue as reported in:
* https://github.com/elk-zone/elk/issues/1696
* https://github.com/elk-zone/elk/issues/1427

**Comment by shleeable** [comment]
I can confirm this is using docker.

**Comment by shleeable** [comment]
This seems to be resolved with the updated instruction. v0.7.5 is running on https://elk.aus.social

**Comment by shleeable** [comment]
this was resolved by fixing the permissions on the docker elk-storage
`chown 911:911 elk-storage/`
