### ISSUE TITLE
Elk doesn't respect default setting of "followers-only" on locked accounts

### ISSUE THREAD

**Issue by smiba** [elk-zone/elk#1756]
Hi! 

Today after posting about some personal stuff on my locked account (account that has manual follower approval enabled), I got notified after an hour that this has instead been posted as "public"

On mastodon and some/most clients the default behaviour on accounts like this is to also mark the posts as "follower-only", unless you explicitly select differently.

I'd love to see this implemented in Elk, because I know this will probably happen to me again 😬😅
Not sure if it should be listed as a bug, but considering the impact of it and the deviation from default behaviour I'd say it is.

**Comment by peterbud** [comment]
See #1733 - on it's way hopefully

**Comment by smiba** [comment]
> See #1733 - on it's way hopefully

Awesome! Thanks for you work 💜

**Comment by smiba** [comment]
Has been fixed for a while now, closing it :)
