### ISSUE TITLE
`pnpm esno scripts/prepare-translation-status.ts` fails

### ISSUE THREAD

**Issue by sapphi-red** [elk-zone/elk#1789]
#1597 changed `i18n-ally.sourceLanguage` to `'en'`.
That change made this line to return `undefined`.
https://github.com/elk-zone/elk/blob/fb01c467cb90675adae12404ea7d7f850c5d7e7d/scripts/prepare-translation-status.ts#L68
Now `pnpm esno scripts/prepare-translation-status.ts` fails with an error.

This can be reproduced by opening the code flow: https://pr.new/elk-zone/elk

**Comment by userquin** [comment]
@sapphi-red should be fixed: #1790

**Comment by userquin** [comment]
fixed on #1790
