### ISSUE TITLE
Add template case for admin.report notifications

### ISSUE THREAD

**Issue by fihu** [elk-zone/elk#1809]
Similar to `notification.type === 'admin.sign_up'` in `NotificationCard.vue`, Masto 4.0's notification for new reports should be displayed.

Notification type is `admin.report`, currently an error is shown:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/14976291/220869774-e49ee4ef-3fe9-4af2-be70-6175b271e5f0.png">

**Comment by djwfyi** [comment]
It'll only apply to moderators and other admins, but it would be nice for those of us that fall in that umbrella to see these handled gracefully. Maybe include an original link to the report so we can take action on it.
(There's not really a need to build out all of the admin functions in Elk, I don't think. But being able to click the report notification and open a separate tab to view the report would be amazing.)

Semaphore handles these notifications, but doesn't provide a link to the report page.

**Comment by patak-dev** [comment]
This is a good issue if someone would like to contribute to Elk.

Here is the notification data for `admin.report`: https://docs.joinmastodon.org/entities/Admin_Report/

And to implement this a new branch should be added after `admin.sign_up` to show the data here: https://github.com/elk-zone/elk/blob/3732a2cc16b4de6cd60f4836151d4a3292c627fa/components/notification/NotificationCard.vue#L32

I imagine it should show at least the `account`, the target account, the category. I don't see a URL for the report though @djwfyi. Maybe there should be a link that goes directly to the admin setting in your server.

**Comment by djwfyi** [comment]
At least for Mastodon, the link would be https://domain.tld/admin/reports to get to the standard page.
The report itself is just that with the report number added at the end:`/##`
Something like: https://domain.tld/admin/reports/2

Either a link to the list of reports or a link to the specific report would be nice.

**Comment by kytta** [comment]
I took a swing at it in #2045 and need some help with it 🙋🏻‍♂️

**Comment by kytta** [comment]
#2045 is now ready for review

**Comment by fihu** [comment]
Thanks! The commits look way more complicated than what I tried out myself. Good job!
