### ISSUE TITLE
Even more grouping of Favorited and Boosts

### ISSUE THREAD

**Issue by fgeierst** [elk-zone/elk#1819]
Notifications view: Elk already does some grouping when more people favorite and/or boost a post. This fine for most of the time, but when a post gets lots of attention that very long lists of heart icons and usernames becomes less useful (screenshot).

My proposal is to above a certain threshold of boosts/favs don’t display user names at all and instead just show two counts once a day: number of favs / number of boosts.

![B133D649-0B10-4CB7-A147-D5974A7DC2DA](https://user-images.githubusercontent.com/22551442/221146565-ae81834d-11c8-44b6-8e9b-1b69f6118894.png)

**Comment by durka** [comment]
Looks like this was implemented recently. Personally, I don't like it. The profile images are too small and non-unique. I think a preferences entry for this might be nice.

**Comment by fgeierst** [comment]
Yes, I’ll close this as resolved. You might want to make a follow up ticket to make this configurable.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/22551442/229338322-a572f20d-374e-4032-bbce-86474aedfdda.png">
