### ISSUE TITLE
Always copy the URL of the original post

### ISSUE THREAD

**Issue by trickjarrett** [elk-zone/elk#1861]
When I click the triple dots menu on a post to copy the URL, I cannot think of a reason where I would want to copy the URL via my local server rather than the URL to the original post. Can we have an option which makes it the default, if not simply make it the default?

**Comment by patak-dev** [comment]
When you press the three dots, both URLs you can copy are pointing to the original post (the first through Elk, and the second one direct to the server). This is already working as expected. Maybe you would like to avoid having the first one be a link to Elk? For the moment, we believe that most of our users would prefer to share the post using Elk and we need to avoid adding too many options. We may review this in the future though as it is something that has been brought up before.
