### ISSUE TITLE
Add "hide following count" to Wellbeing options

### ISSUE THREAD

**Issue by moopet** [elk-zone/elk#1878]
The "wellbeing" options in settings allows users to choose "hide follower count", but not "hide following count".

I think either it should be a new option, or the existing option should cover both cases, not least because I always forget which one is which and end up having to experimentally set options to see what they've done.

**Comment by patak-dev** [comment]
I would prefer that the current option would also hide the following count. If a user doesn't care about how many folks are following others, I don't think the following count would be interesting to them. PR welcome if you or someone else would like to work on this one.
