### ISSUE TITLE
Profile editor messes up User Picker

### ISSUE THREAD

**Issue by mk-rexx** [elk-zone/elk#1879]
Saving profile in profile editor duplicates curently active user to other items in User Picker. 
[Video](https://imgur.com/a/UVJmAgV.mp4)

How to reproduce:
1. Select the 2nd account on User Picker
2. Go to own profile
3. `Edit profile`
4. Update profile then `Save`

Fixes itself by reloading the page. 
Also reproducible even if Settings>Prefferences>Experimental Features>User Picker is unticked. Difference is doesn't fix itself by reloading page. 
Not reproduceable when active user is the first item in User Picker.

Pardon if I'm doing something wrong, this is my first time submitting an Issue

**Comment by patak-dev** [comment]
Thanks for creating the issue @mk-rexx! I can also reproduce it.

**Comment by userquin** [comment]
@patak-dev it seems we're handling acct in a different way on account and cache modules, I'm checking it.

We're overriding some crucial info, acct being saved raw, we need to add the server and override it in account cache, sending PR...
