### ISSUE TITLE
Show selected answer on poll view

### ISSUE THREAD

**Issue by EddiesTech** [elk-zone/elk#1889]
Currently, if you answer a poll, the results show, but you cannot see the answer you selected. Perhaps a tick next to the one you selected like on the Mastodon UI. Would use `own_votes` in the API I think.

https://docs.joinmastodon.org/entities/Poll/#own_votes

**Comment by Shinigami92** [comment]
Is this already implemented?

![image](https://user-images.githubusercontent.com/7195563/236537966-c0a07538-1154-430b-9847-e123363eacca.png)

https://github.com/elk-zone/elk/blob/5ffb96baf6ddf88334d41b19e601afac8283beed/components/status/StatusPoll.vue#L65

This could potentially get closed, can it?

**Comment by EddiesTech** [comment]
Hi @Shinigami92. Yes, this must have been added at some point :)
