### ISSUE TITLE
displaying the wrong profile on hover from avatar and username

### ISSUE THREAD

**Issue by wakest** [elk-zone/elk#1913]
easiest to just watch this screencast to explain
https://user-images.githubusercontent.com/7890201/226399871-fa4cd225-0ceb-4d2a-b302-6cf76737c99d.mov

this is showing up on canary [60924e5](https://github.com/elk-zone/elk/commit/60924e5f5d537aa86fd63fc8c02f3f044bf35ffe)

seems to show up on [this thread](https://elk.zone/social.wake.st/@mastodonusercount@mastodon.social/110051958259532097) and i haven't found other threads it happens on yet

**Comment by wakest** [comment]
bug is present on elk.zone ([v0.7.5](https://github.com/elk-zone/elk/releases/tag/v0.7.5)) as well just tested it

**Comment by EddiesTech** [comment]
MP4 version of video to view in browser:
https://user-images.githubusercontent.com/13002124/226485913-66c7ad16-ac3e-405a-894f-b6a307d35b5e.mp4
