### ISSUE TITLE
Editing a post with an emoji causes corruption, emoji conversions

### ISSUE THREAD

**Issue by rpavlik** [elk-zone/elk#1932]
If you have an emoji in the middle of a post, and you try editing it, most edits at the end will cause mangling of your changed text, with things turning into emojis.  Depending on the emoji, it also seems like sometimes it is getting split into separate unicode codepoints in which case it will be one invalid one and one emoji, the server will reject the message, and you have to delete the invalid one (and risk more conversion) to actually post the edit.

As you can see in the video, I discovered the emoji has to be in the middle of the post to trigger the error. I'm using Elk as a PWA "installed" using Chrome on Android.

https://user-images.githubusercontent.com/61129/228559145-b15063a2-f4e4-4015-884d-8a5c867a148e.mp4

**Comment by rakslice** [comment]
This basically makes the edit function unusable which makes elk unusable; you should really fix this

**Comment by rakslice** [comment]
Note that this also effects just using Elk in regular browser mode, not just "installed" PWA, and on platforms other than Android
