### ISSUE TITLE
Changing profile links when there are multiple profiles 'corrupts' other profiles

### ISSUE THREAD

**Issue by pandaninjas** [elk-zone/elk#1941]
After changing a profile link, the other profiles seem to be corrupted in a weird way. It goes back to normal after clicking the profile again, but there are many weird symptoms of this 

Video illustrates this bug:

https://user-images.githubusercontent.com/101084582/229297822-3661be80-fd6a-4d2d-a4cf-24b5f3d507e8.mp4

**Comment by userquin** [comment]
duplicated of #1879
