### ISSUE TITLE
video fullscreen button is disabled

### ISSUE THREAD

**Issue by allenli178** [elk-zone/elk#1942]
![截屏2023-04-02 09 59 23](https://user-images.githubusercontent.com/53218750/229327033-23267986-7d8e-4ac7-95d8-9f5d1da51ea9.png)

**Comment by alexzhang1030** [comment]
This was intentional, as we need to consider the browsing experience on mobile devices. Therefore, we have set the playsinline attribute.

**Comment by Alex0007** [comment]
@alexzhang1030 i clicked on the post, but still unable to open video in fullscreen mode.. 🤔

**Comment by edolis** [comment]
Yes, please fix this.
It is a major usability issue-the only way which I currently found to play the videos fullscreen is the copying a link to the original post and then opening the video in the standard mastodon interface.
