### ISSUE TITLE
Link preview not displaying correctly

### ISSUE THREAD

**Issue by brendanjones** [elk-zone/elk#1948]
When posting this link https://www.opendemocracy.net/en/oureconomy/corporate-monopolies-are-threat-to-democracy-public-interest/ here https://fosstodon.org/@Brendanjones/110135158010222739, it was displayed in the link preview on Elk like this, missing the header and subheader:

<img width="595" alt="Screenshot 2023-04-03 at 15 40 14" src="https://user-images.githubusercontent.com/16049594/229528521-8aa73a38-096e-425c-a042-28eba3ad9dff.png">

I thought it might be a problem with that website but on Mastodon native it looks fine:

<img width="578" alt="Screenshot 2023-04-03 at 15 41 51" src="https://user-images.githubusercontent.com/16049594/229528533-d9d9d203-258a-4405-9b38-4080535c92aa.png">

Also displays fine on the birdsite (nope, didn't post, I'm not using that website anymore, just for Elk bug testing :p ):

<img width="528" alt="Screenshot 2023-04-03 at 15 43 03" src="https://user-images.githubusercontent.com/16049594/229528569-923379e9-5048-499c-93bd-09470b2e0b3e.png">

**Comment by patak-dev** [comment]
It should work in https://main.elk.zone now (soon when deployed and you upgrade). Thanks for the report!
