### ISSUE TITLE
bug: Incorrect character count on compose box

### ISSUE THREAD

**Issue by djwfyi** [elk-zone/elk#1977]
When composing a message, I had a character count of 496 characters out of my instance's 500 limit.
But when I went to publish it, I got a validation error that the character limit of 500 was exceeded.

When I posted the same text into the vanilla Mastodon web UI, it counted it as 501 characters, so the validation was correct. But the character count for the compose box was not.

![image](https://user-images.githubusercontent.com/53910321/231899847-2b14c29a-44d1-4010-80bd-49c9de024d42.png)

**Comment by alec-lefors** [comment]
In case anyone else wants a crack at it you can copy and paste this [https://pastebin.com/raw/Ysqwie3C](https://pastebin.com/raw/Ysqwie3C) (pastebin to avoid github formatting) the issue is with the https://semaphore.vmst.io/ link
