### ISSUE TITLE
Allow user-configurable choice of preferred profile picture shape (※ Circle, squircle, rounded square, square, etc.)

### ISSUE THREAD

**Issue by akemin-dayo** [elk-zone/elk#1980]
It seems that Elk has changed the shape of the profile picture element from a circle to a squircle at some point.

It would be nice if the profile picture shape was instead controlled by a user-configurable preference in perhaps the "Interface" preference pane instead, for those who prefer to see a different shape for profile pictures. (※ I personally prefer circular profile pictures.)

Common shapes for profile pictures include:
* Circle
* Squircle
* Rounded square
* Square

**Comment by patak-dev** [comment]
Hey @akemin-dayo! Thanks for the proposal. I'm afraid we already have a lot of configuration options so for the moment I think we should try to keep the current scheme with avatars. We can review this in the future if more people are interested.
