### ISSUE TITLE
Favicon has white square background in Firefox bookmarks

### ISSUE THREAD

**Issue by vintprox** [elk-zone/elk#1988]
I'm not sure if it's purely Firefox issue here or something's weird in the setup of favicon, but it looks not very pretty for me:

![image](https://user-images.githubusercontent.com/5708819/232413826-957ea586-4936-4bce-b19f-6da30a2d002d.png)

I find this in the page sources, which makes me wonder if the issue is related to `*.ico` or `*.svg` icon:

```html
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/svg+xml" href="/logo.svg">
```

Can't really understand which one is used, but I'd assume the SVG one.

**Comment by EddiesTech** [comment]
I exported both of those files. They are both transparent! Perhaps Firefox is using a cached version, but I think it has always been transparent.

**Comment by vintprox** [comment]
> Perhaps Firefox is using a cached version, but I think it has always been transparent.

That's weird. I made sure to clear the cache and restart the browser and result is the same white background under the elk. Color picker positively shows #ffffff, even though nothing in the source SVG suggests a use of white.

It's Firefox being finicky, I suppose. No other importer suggests that background should appear, it's transparent in fact.

**Comment by vintprox** [comment]
Ah, there is an "apple-touch-icon" unaccoutnned for when I first discovered the issue. It's something related to resolution and that jazz, the explainer is [there](https://bugzilla.mozilla.org/show_bug.cgi?id=1701939#c3). Firefox has an [open issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1494016) in regards.
