### ISSUE TITLE
Custom emojis are not rendered in the profile metadata

### ISSUE THREAD

**Issue by BlackLight** [elk-zone/elk#1992]
My instance has a few local custom emojis.

These emojis are rendered fine in posts, and even detected when typing `:...` in the compose textbox, but they aren't rendered when used in the profile metadata fields.

How it looks on the official Mastodon client:

![Screenshot_2023-04-18_16-16-34](https://user-images.githubusercontent.com/42405/232805681-8b75eef0-80b7-4912-87c4-bb2eedd9ba3d.png)

How it looks on Elk:

![Screenshot_2023-04-18_16-17-14](https://user-images.githubusercontent.com/42405/232805899-bb842993-0cbc-418f-96ad-10a05c87b66a.png)

**Comment by patak-dev** [comment]
Thanks for the report, you can test it at https://main.elk.zone or wait for the next release.
