### ISSUE TITLE
Broken image icon when local media can't be loaded

### ISSUE THREAD

**Issue by EddiesTech** [elk-zone/elk#2010]
Sometimes my VPS has an issue with the DNS so it doesn't download the images to local storage. On Elk, the blurred version loads in fine, but then when the local media is loaded (or not loaded in more like) the blurred image goes and is replaced by the broken image icon. Is it possible to do the same as the Mastodon client and display an error message over the blurred version? This would mean the timeline wouldn't jump about when the local image URLs are attempted.
Elk:
![image](https://user-images.githubusercontent.com/13002124/233871901-1f440c7f-d7a7-441c-9c50-39e981ad85a3.png)
Mastodon:
![image](https://user-images.githubusercontent.com/13002124/233871908-d0f53873-60a8-4cbe-a116-8b2f9051f0ff.png)

**Comment by patak-dev** [comment]
This seems fixed now after merging https://github.com/elk-zone/elk/pull/1969
Please re-test @EddiesTech and lets reopen if you see the issue again
