### ISSUE TITLE
Allow unfollowed accounts to be added to lists

### ISSUE THREAD

**Issue by pixiekat** [elk-zone/elk#2022]
Like how Twitter works, I like to use lists to create multiple secondary timelines without cluttering up my main timeline. 

To do this, I would add accounts to one or more lists while not following them, so they don't show up in the regular timeline. I used to be able to do this normally on Twitter but on Mastodon I don't even have the option to add to a list without following them first (so what I do is follow and then mute, which isn't ideal). 

Is it easy enough to allow unfollowed accounts to be added to lists or should I post in the actual Mastodon repo?

**Comment by boehs** [comment]
Hi. Thanks for the issue. We've had lots of discussion about this feature in #372, but the gist is that we want to do this in a responsible way (and yes, the lack of it is a mastodon "feature"). See also #1586.

Cheers
