### ISSUE TITLE
Merge boosted replies into boost

### ISSUE THREAD

**Issue by SoniEx2** [elk-zone/elk#2030]
If you boost a post, and your own reply to that post, then your reply should appear inside the original post rather than as a separate boost.

It'd look great! That's the only reason really.

(Kinda like a "threaded view", but only for one reply.)

**Comment by patak-dev** [comment]
We already do this AFAICS, would you create some mocks or a PR to show the diff you are proposing?

**Comment by SoniEx2** [comment]
they should look something like this: https://communitynotes.twitter.com/guide/en

but on a boost, it'd show the boosted account's icon, with the booster's icon, and *also* the booster's reply - the latter one would look like one of those twitter community notes, in that it goes inside the post.

**Comment by patak-dev** [comment]
Thanks for the proposal, but I think the current way we show boost + boosted replied is better. What you show here looks more like quote posts, hopefully coming in a future Mastodon update.

**Comment by SoniEx2** [comment]
no, it's the complete reverse of quote posts. it's for fact checking and whatnot.
