### ISSUE TITLE
Support web+ap

### ISSUE THREAD

**Issue by SoniEx2** [elk-zone/elk#2033]
Hello. Could you please add an endpoint for shoving component percent-encoded web+ap URIs into, and add it to the PWA manifest?

**Comment by patak-dev** [comment]
Please give more context when you create an issue, and explain cleary why you need this.

**Comment by SoniEx2** [comment]
It would make elk compatible with fedicraft, a minecraft mod. In the long-term the plan is to make it so ppl can link activitypub objects and open them in their preferred client, with the original instance only opening if the user doesn't have a preferred client.

**Comment by patak-dev** [comment]
Thanks for the proposal, I think in this case the best is for the fedicraft community to maintain a fork of Elk. And later on, if we publish Elk to npm, maybe migrate to using it as a Nuxt Layer.
