### ISSUE TITLE
Feature request - always show media and always show content with warnings

### ISSUE THREAD

**Issue by acroyear** [elk-zone/elk#2057]
This is the one missing feature that is keeping me from using Elk as often as I like, given that the rest of the interface and feature set (esp threading) is fantastically done.

In the Mastodon official UI there are 2 options I enable - **always show media** and **always expand posts with content warnings**. I have both of these on because as i'm doomscrolling :) I just want to mouse-wheel or trackpad scroll. I don't want to have to move my mouse to hit the button to see images. I know what I'm subscribed to (and if i don't like something, I'll block it). The extra physical work to go and open these is annoying, and somedays painful (i'm in my 50s and been typing and mouse-moving for 30 years now).

I would like to just scroll down and see everything without having to take extra action to do it.

**Comment by jasonbrooks** [comment]
there's an existing issue about this: #1002

**Comment by acroyear** [comment]
closing as dup, then.

I did search but seemed to have missed a keyword to get that issue to stick out.
