### ISSUE TITLE
Post composing language should use the preferred settings of the profile

### ISSUE THREAD

**Issue by hanan-cohen** [elk-zone/elk#2079]
In Preferences > Other > Posting defaults > Posting language

My setting is Hebrew - עברית

![2023-05-07 11_24_10-Preferences - Toootim — Mozilla Firefox](https://user-images.githubusercontent.com/15553877/236666547-e114e5ef-8d3f-44ff-9509-645120d76826.png)

In Elk ( v0.9.5) - the language is always English

![2023-05-07 11_28_12-Compose _ Elk — Mozilla Firefox](https://user-images.githubusercontent.com/15553877/236666612-33190ff8-63bb-41e4-873d-89a02e6c5c06.png)

**Comment by moeffju** [comment]
See also #876
