### ISSUE TITLE
Elk shows "Media hidden" but there is no media to show

### ISSUE THREAD

**Issue by sbug0** [elk-zone/elk#2090]
In this post https://elk.zone/mastodon.social/@Pwnallthethings/110341838593089566 , Elk shows info about hidden media, however the post does not have any media to show.

The following images shows hos Elk renders the post.

Without klicking "Media hidden":
![elk1](https://github.com/elk-zone/elk/assets/122732288/635b0fb8-3516-446e-ad5c-313376aa212b)

When klicking "Media hidden":
![elk2](https://github.com/elk-zone/elk/assets/122732288/0832364f-85f9-4898-b7e2-a178f2b9875e)

**Comment by userquin** [comment]
It seems the server is sending empty `spoilerText` and we're checking it is present only:

https://github.com/elk-zone/elk/blob/main/components/status/StatusContent.vue#L24

![imagen](https://github.com/elk-zone/elk/assets/6311119/6262b8b1-dd4f-4bcc-9c22-dc0ad2dad9e8)
