### ISSUE TITLE
Give users ability to change the keyboard shortcuts , because ctrl + c being overriden is annoying  when you normally use ctrl + c to copy a text selection

### ISSUE THREAD

**Issue by BugDevelopments** [elk-zone/elk#2110]
Give users ability to change the keyboard shortcuts , because ctrl + c being overriden is annoying  when you normally to use ctrl + c to copy a text selection.

**Comment by rockfordlhotka** [comment]
At least on Windows it seems like there's a bug here where ctrl-c and c are treated the same - like the JavaScript that's hooking the keyboard for c isn't filtering out ctrl-c.

**Comment by BugDevelopments** [comment]
Seems like someone fixed it. Thanks.

**Comment by shuuji3** [comment]
Thanks for the update. Glad to hear that.🙂 Probably because we recently fixed some keyboard shortcut issues. I'm closing this but feel free to reopen it if you encounter the same one.
