### ISSUE TITLE
Selected text selection is not when visible `experimental-web-platform-features` flag is set

### ISSUE THREAD

**Issue by tomayac** [elk-zone/elk#2147]
![Screenshot 2023-06-05 at 14 08 18](https://github.com/elk-zone/elk/assets/145676/347a4e52-c991-40e5-9315-7af819a05050)

The CSS color variable `--c-bg-selection` is not defined. The reason is outlined in this blog post: https://www.azabani.com/2022/09/01/meet-the-css-highlight-pseudos.html#accessing-global-constants, including some workarounds.

**Comment by shuuji3** [comment]
I think this was already fixed by #2222
