### ISSUE TITLE
bug: Image lazy-loading not working.

### ISSUE THREAD

**Issue by leopku** [elk-zone/elk#2172]
![](https://i.imgur.com/tpFEtGw.png)

Image lazy-loading not working and images broken.

Images show correctly if change attribute from `data-src` to `src` in inspector.

**Comment by kimusan** [comment]
this seems to be similar to https://github.com/elk-zone/elk/issues/2140

**Comment by leopku** [comment]
@kimusan Right.

I would close this issue and refer it to #2140.
