### ISSUE TITLE
Polls with no end date show as "ends 53 years ago"

### ISSUE THREAD

**Issue by SteveDinn** [elk-zone/elk#2175]
View [this post](https://calckey.social/notes/9g2fpdc2odk4pwqf) in Elk and you'll see that it is reported as ending 53 years ago.

![image](https://github.com/elk-zone/elk/assets/3911507/c32bee72-198d-4161-a70c-ca8d6c6cdf2f)

**Comment by userquin** [comment]
@SteveDinn can you test it in the PR preview when ready (or provide a link for Elk)?

**Comment by userquin** [comment]
Since `expireAt` is undefined, `useTimeAgo` will use 0 and so `2023 - 1970 = 53`.
