### ISSUE TITLE
docs.elk.zone does not work (properly)

### ISSUE THREAD

**Issue by daudo** [elk-zone/elk#2223]
I was interested in the PWA documentation https://docs.elk.zone/docs/pwa mentioned in README.md, but unfortunately the page would only display a never ending animated loading icon.

Then I tried to access https://docs.elk.zone/ only and while this showed some content, the page looks seriously broken. I then tried to access the site in private/incognito mode, to no avail. Tried with both FF and Chrome.

When inspecting the page in FF, the network tab shows loads of 404s and entry.js is not loaded at all, because "Loading module from “https://docs.elk.zone/docs/_nuxt/entry.0e948067.js” was blocked because of a disallowed MIME type (“text/html”)"

![image](https://github.com/elk-zone/elk/assets/360141/93fe056b-1a38-4480-bb1b-8374bbc447d0)

**Comment by userquin** [comment]
should work now, fixd via https://github.com/elk-zone/elk/commit/895c1ecd8dd6128a7d7334d9c978ba825542a20b
