### ISSUE TITLE
Confirmation dialog for delete-and-redraft

### ISSUE THREAD

**Issue by durka** [elk-zone/elk#2291]
There is a confirmation for deleting a toot, but not for deleting and redrafting one. Yeah, it's a less destructive operation because you have the toot content there again in the popup, but it can still break threads, lose boosts etc so I think there ought to be a confirmation.

**Comment by shuuji3** [comment]
I also agree and this is a reasonable assumption since both actions are colored red on the menu and it's dangerous actions.
