### ISSUE TITLE
Editing a Post removes indentation

### ISSUE THREAD

**Issue by laundmo** [elk-zone/elk#2382]
When editing a post on elk.zone, it removes leading whitespace.

post text:
![image](https://github.com/elk-zone/elk/assets/24855949/3939b3e8-9ca9-44a0-aba2-4db2b80e942e)
after opening the editing window:
![image](https://github.com/elk-zone/elk/assets/24855949/3eb633bc-6186-4b9d-afd7-3bc6d2d2b8c8)

**Comment by shuuji3** [comment]
Thanks for your report.🙂

**Additional info:** Interestingly, the following post with a pair of two spaces:

```
test  
  test 
```

resulted in

```
test 
test 
```

`test  ` → `test `.
