### ISSUE TITLE
iPadOS Safari displays status bar with light text in light theme

### ISSUE THREAD

**Issue by reonokiy** [elk-zone/elk#2384]
![IMG_0088](https://github.com/elk-zone/elk/assets/65524316/7b82cae6-629e-4fee-8843-7c153744624e)
![IMG_0087](https://github.com/elk-zone/elk/assets/65524316/ca3c6c17-1ed5-4be8-b1dc-84e6cd9b3204)

I'm using iPadOS 16.6 and using Safari browser. And I added elk.zone site to Home Screen.

As you can see from the first image, the status bar is white and the background is also white color. But in dark theme the text and background display correctly.

Another example is this image. 
![IMG_0089](https://github.com/elk-zone/elk/assets/65524316/2f3da1a4-b10e-4c9b-a152-00197f80403a)

But it cannot change status bar color in dark theme

![IMG_0090](https://github.com/elk-zone/elk/assets/65524316/26f05936-247e-4f34-bd47-f50f88190210)

I don't know if it's possible to fix this for Safari.

**Comment by userquin** [comment]
@reeink Elk will use a custom webmanifest per locale and theme, there is no yet any spec about browser support for pwa theme. The browser will use the theme_color/background_color from the webmanifest or the theme-color in the html head when installing the pwa.

The pwa docs website use a single webmanifest with fixed colors.
