### ISSUE TITLE
mp4 playback

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2387]
I'm having issues with Elk MP4 playback:

https://mas.to/@iamdtms/111030981994584311 vs. https://elk.zone/mas.to/@iamdtms/111030981994584311

Preview image available, not much. 

Thank you: 
iamdtms
https://github.com/iamdtms

**Comment by userquin** [comment]
@iamdtms shuold be fixed with this PR https://github.com/elk-zone/elk/pull/2346, you can check your video here (open the url in private browser to remove the pwa when you close the window): https://deploy-preview-2346--elk-zone.netlify.app/universeodon.com/@iamdtms@mas.to/111030982007126567

**Comment by userquin** [comment]
duplicated #2220
