### ISSUE TITLE
The text editing window is far too small

### ISSUE THREAD

**Issue by jensimmons** [elk-zone/elk#2416]
I don't know what changed or why, but the text editing window is now far too small vertically. It's frustrating to have to keep scrolling up and down in such a tiny window to write a post. 

Could you change it back to how it was? Otherwise Elk isn't really useable for creating posts or replies.

**Comment by patak-dev** [comment]
Thanks for the heads up Jen! We reverted https://github.com/elk-zone/elk/pull/2334). This should now be fixed if you access elk from https://main.elk.zone and it will be in elk.zone in the next release.
