### ISSUE TITLE
@user@server inside profile metadata is read as HTML instead of text

### ISSUE THREAD

**Issue by esthedebeste** [elk-zone/elk#2433]
I have a bot i made in the metadata of my profile, and this breaks the metadata when i update my profile with elk.

Steps (all within elk): 
- Add a metadata tag to your profile @'ing another account (for me that's `@billie_lyrics@botsin.space`)
- Save
- That same metadata tag turns into html code inside of the edit field
- When you save again after that, that html code is escaped (with `&lt;` and the such) and shows as raw text on your profile.

**Comment by snail-coupe** [comment]
I think this is a duplicate of my #1216?

**Comment by esthedebeste** [comment]
yep i believe it is 😅
