### ISSUE TITLE
Anchor href attributes incorrectly encoded on front end

### ISSUE THREAD

**Issue by drzax** [elk-zone/elk#2450]
It seems like URL query params are being URL encoded when they shouldn't be, rendering `&` as `&amp;` and breaking links.

<img width="427" alt="image" src="https://github.com/elk-zone/elk/assets/596563/22fe7021-5505-4543-bb20-836058115fdb">

The same post viewed in the Mastodon interface has the URL encoded correctly:

<img width="485" alt="image" src="https://github.com/elk-zone/elk/assets/596563/d96c3612-2063-4075-9e2c-db87a7eef499">

**Comment by Sma11X** [comment]
Already fixed at #2377 , try it on [canary](main.elk.zone).
