### ISSUE TITLE
video posts display as still images, clicking does not play video

### ISSUE THREAD

**Issue by piebob** [elk-zone/elk#2496]
i'm a relatively new user of Elk, apologies if i'm missing something. i looked to see if this was reported already but simple searching of the open issues did not turn up anything obvious. 

the issue: posts that contain embedded videos don't have any kind of play icon overlaid or show in any other way that they're videos, and when i click, nothing happens. 
here is an example post: 
https://elk.zone/metasocial.com/@catsalad@infosec.exchange/111507061493466045

i noticed via the alt text that this was supposed to be a video. 
i'm using firefox, windows 10.

**Comment by piebob** [comment]
in chrome? i'm using firefox--in case that matters

-rachel

**Comment by piebob** [comment]
also the comments in the PR review seem to apply to gifs, not to videos?

-rachel

**Comment by userquin** [comment]
![imagen](https://github.com/elk-zone/elk/assets/6311119/1bb60ceb-2baa-4c22-b78e-9904fc8a11d3)

**Comment by userquin** [comment]
duplicated #2220

**Comment by piebob** [comment]
hmm, just tried this link and it works very intermittently, often fails to play, even after a shift reload
https://deploy-preview-2346--elk-zone.netlify.app/universeodon.com/@bleuje@mastodon.social/111523512234030612
