### ISSUE TITLE
Support 3x3 Grid Image Layout

### ISSUE THREAD

**Issue by CDN18** [elk-zone/elk#2502]
Mastodon traditionally allows a maximum of four images in a single post. However, other servers, such as Gotosocial, support a higher maximum number of images or allow for customizing this number. 

Currently, posts with more than four images are displayed in a single column. A 3x3 grid layout would provide a more organized and visually appealing presentation, enhancing user experience.

**Comment by HawtinZeng** [comment]
This feature is required too, how do u think @antfu
