### ISSUE TITLE
Pending follow request show as rejected

### ISSUE THREAD

**Issue by coxde** [elk-zone/elk#2531]
Hello! I host a [GoToSocial](https://github.com/superseriousbusiness/gotosocial) instance, a Mastodon API compatible software. 

I found out that when other accounts try to follow a locked account, the follow request would show as "You have rejected the request" in notifications. But actually the request is still pending, and other frontend like [Semaphore](https://github.com/NickColley/semaphore) can correctly handle it. If I use Semaphore to approve this request, Elk can correctly show "someone follows you" and the rejected notification would go.

I can confirm that I can reproduce this bug by using different accounts to test it.

GoToSocial version: [0.13.0 git-f4fcffc](https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.13.0)
Elk version: v0.10.3 and it's https://elk.zone/

Thank you!

**Comment by Sma11X** [comment]
Thanks for the feedback. Do you mean the notification card will always show the text instead of showing the handle buttons ?

**Comment by coxde** [comment]
> Thanks for the feedback. Do you mean the notification card will always show the text instead of showing the handle buttons ?

Yes, it always shows "You have rejected the request" instead of buttons.

**Comment by Sma11X** [comment]
Unfortunately GoToSocial's relationship API lack of a attribute `requested_by` and it only has `requested`. The latest mastodon use `requested_by` to determine if the user has send the follow request.
It would cause other issues if elk were made compatible.

**Comment by coxde** [comment]
Thanks your clarification, I'll forward this to GtS and see what they think.
