### ISSUE TITLE
Character limit error for being over 500 when it's clearly marked as under

### ISSUE THREAD

**Issue by FiniteLooper** [elk-zone/elk#2538]
So I wrote this toot

```
I built a simple site using .NET Core 6, and it was way overkill. It's just a static site. Building and deploying is a bit of a nightmare for what should be simple.

Then I found Eleventy yesterday, and this is a huge game changer! Much much simpler and more sane for simple static sites like this one. Learned Eleventy and re-wrote it all in about a day. Dead simple, just had to figure out how to do some configuration stuff and post-build steps

Very impressed with this project: http://11ty.dev
```

Elk's UI reports it as being 496 characters long.  If I paste it into the JS console as a string and get the `.length` that reports 498 characters.  Inconsistent, but still under the 500 character limit.  Yet when I go to post it says I am **over** the limit!

I had to remove a few more words to allow me to post.

Here's a screen recording of this happening
![elk-error](https://github.com/elk-zone/elk/assets/463685/15135ab2-5587-42aa-ab74-9dbe0f9a32f2)

**Comment by Pfaufisch** [comment]
From https://docs.joinmastodon.org/user/posting/#links

> All links are counted as 23 characters, no matter how long they actually are, so there is no need to use a link shortener to save characters. In fact, using a link shortener is actively discouraged.

Your text without the URL is 483 characters, + 23 = 506

**Comment by boehs** [comment]
#1880
