### ISSUE TITLE
Notifications not loaded

### ISSUE THREAD

**Issue by haayman** [elk-zone/elk#2599]
I'm seeing this for a couple of days now.
Whenever I get a notification, the menu shows there are notifications, but when I click it the notifications don't get loaded.
I have to reload the entire page to seem them.

I'm running canary b9394c2

**Comment by wezm** [comment]
I'm running 0.11.0 (https://github.com/elk-zone/elk/commit/9f005a0a590e317610913874b8280fd9f52b9518) and seeing the same behaviour.

https://github.com/elk-zone/elk/pull/2566 seems like the most relevant change either that or the the masto.js upgrade itself https://github.com/elk-zone/elk/pull/2530

**Comment by wezm** [comment]
Confirming this is still an issue in Elk 0.12.1

**Comment by kushaldas** [comment]
Same here with version: [v0.12.1](https://github.com/elk-zone/elk/releases/tag/v0.12.1) , really irritating bug. Using on `Firefox 123.0`

**Comment by kevteljeur** [comment]
Same here, Firefox 123.0 on Mac. Saw this with the previous minor build of Elk too.

**Comment by mediapinta** [comment]
Same here using on LibreWolf 123.0-1 and on Tangram 3.0
