### ISSUE TITLE
'replying to' not displayed in canary

### ISSUE THREAD

**Issue by haayman** [elk-zone/elk#2608]
Very recently I'm seeing no 'replying to' headers on replies in the main timeline

I'm running the canary branch

(somehow I'm not able to make screenshots of anymore of elk pages. is this prevented somehow?)

**Comment by haayman-imagem** [comment]
alas
in main: 
![afbeelding](https://github.com/elk-zone/elk/assets/58473220/eee35bd9-1cb9-404a-ba1a-3ef4c5c31628)

in canary:
![afbeelding](https://github.com/elk-zone/elk/assets/58473220/926f32b6-0916-4211-a580-e49d45592179)

**Comment by haayman-imagem** [comment]
it may be worse even: entire conversation snippets disappear. Compare main
![afbeelding](https://github.com/elk-zone/elk/assets/58473220/c1c89084-3879-40f0-a94b-fda05a86b7a7)

with canary:
![afbeelding](https://github.com/elk-zone/elk/assets/58473220/00e03166-334a-476f-b29e-f2d2bd4ce83e)

The second conversation snippet doesn't appear at all in canary

**Comment by shuuji3** [comment]
@haayman-imagem Thanks for checking. Just to confirm, do you have the latest version of canary (6dc5a68@main)? You can check on the page: https://main.elk.zone/settings/about

**Comment by haayman-imagem** [comment]
yes

**Comment by shuuji3** [comment]
OK, thank you for double check. Then, it seems that we still have another issue with this. I'll check if I can find something related.

**Comment by shuuji3** [comment]
Now I can see the exact issue 🙂 This is helpful for debugging!

![Screenshot from 2024-02-29 00-38-51](https://github.com/elk-zone/elk/assets/1425259/52b34f6f-df28-4153-91bc-7c4241c00ea7)

![Screenshot from 2024-02-29 00-38-43](https://github.com/elk-zone/elk/assets/1425259/3c5bf2ad-7310-4cd8-8b38-ce809c0e2ea0)

**Comment by userquin** [comment]
@shuuji3 interception observer approach...

**Comment by userquin** [comment]
about StatusCard, status is shadowed with props.status: we'll need to review what's the proper status to use in the template.

**Comment by haayman** [comment]
can confirm it is fixed. Thanks!
