### ISSUE TITLE
Elk completely stopped working on iOS 15

### ISSUE THREAD

**Issue by bitbonk** [elk-zone/elk#2609]
Elk does not work at all anymore on iOS 15 (15.8.1). It also does not work anymore when installed as PWA.

I am getting the below error anywhere.

TypeError: AbortSignal.timeout is not a function. (In 'AbortSignal.timeout((t=this.props.timeout)!==null&&t!==void 0?t:FO)', 'AbortSignal.timeout' is undefined)

![image](https://github.com/elk-zone/elk/assets/418030/ba29e293-c2a6-4d4d-a49f-889f6f565ac2)

**Comment by Shinigami92** [comment]
I can confirm that on iOS 17 (17.3.1) everything is working fine.

**Comment by DasLixou** [comment]
Same here, also on iOS 15

**Comment by userquin** [comment]
It seems a problem with masto v6: https://github.com/elk-zone/elk/blob/6f7efc9f32b55be360edc69bc88bc04ea9864599/tests/setup.ts#L2

/cc @patak-dev should we include a polyfill for this?

**Comment by userquin** [comment]
https://github.com/neet/masto.js/issues/1097#issuecomment-2076195796
