### ISSUE TITLE
Double replies for every mention 

### ISSUE THREAD

**Issue by haayman** [elk-zone/elk#2672]
As of today I'm seeing double replies for everyone mentioned in the toot
![image](https://github.com/elk-zone/elk/assets/683823/bb9c9404-1b57-40d6-b2b9-81b1a7ac4790)
![image](https://github.com/elk-zone/elk/assets/683823/dcf8d392-8bba-4f2f-8d79-bf2ae0245a95)

I'm running canary 0fd9374

**Comment by haayman** [comment]
it seems it has been a hickup. Haven't seen it again

**Comment by shuuji3** [comment]
I hope some changes fix this issue. Feel free to reopen the issue if you reencounter the same issue.
