### ISSUE TITLE
Need a arm64 docker image in GitHub packages 

### ISSUE THREAD

**Issue by yeahwong** [elk-zone/elk#2682]
There is only amd64 docker image in [GitHub packages](https://github.com/elk-zone/elk/pkgs/container/elk), could make a arm64 docker image? Thank you.

**Comment by shuuji3** [comment]
@yeahwong Hi, we've added `linux/arm64` architecture support to `main` (canary) version you can try now. Please wait for the stable version unitl the next version update. Let us know in case you found an issue in arm64 version.

**Comment by yeahwong** [comment]
> @yeahwong Hi, we've added `linux/arm64` architecture support to `main` (canary) version you can try now. Please wait for the stable version unitl the next version update. Let us know in case you found an issue in arm64 version.

Thank you.
