### ISSUE TITLE
Feature Request: Reactions

### ISSUE THREAD

**Issue by cyrneko** [elk-zone/elk#2701]
Reactions are a feature that is widely used in Mastodon forks, like Chuckya or Glitch-soc, that are currently not usable in Elk.

In the Notifications page, reactions are currently indicated as:
```
[DEV] MISSING notification.type: 'reaction' 
```

In the timeline, reactions do not appear anywhere at all.

This is an issue for anyone that uses a nonstandard Mastodon instance, as this will clutter up the notifications page, and it means content will be missing from the timeline.

**Comment by shuuji3** [comment]
Created an issue for actual reaction implementation, not just hiding notification: #3029
