### ISSUE TITLE
Once you leave the browser tab, Elk won't update a GoToSocial account without refreshing the entire web page

### ISSUE THREAD

**Issue by passthejoe** [elk-zone/elk#2706]
Elk will not update and bring in new entries for my GoToSocial account (version 0.14.2, but true for the late few versions) after I leave the browser tab in which Elk is running and then return. To get new entries, I need to reload the entire web page.

This behavior is the same in Firefox and Chrome.

Elk will refresh my Mastodon account with no issues. I only have this problem with GoToSocial. And Semaphore is able to refresh the GoToSocial account without needing a reload of the page.

**Comment by illfygli** [comment]
Encountering the same issue.

Perhaps relevant error message:

```
WebSocket connection to 'wss://…/api/v1/streaming' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
(ónefndur) @ CmsrFQJF.js:29
a @ CmsrFQJF.js:29
```
Works in Semaphore, I see a websocket connection established in the web inspector.

**Comment by illfygli** [comment]
Probably a duplicate of #2427, which might get fixed in GtS soon.

**Comment by shuuji3** [comment]
Thanks for checking other issues I'm closing this now. 

Feel free to reopen if you find the issue's cause differed from #2427. Thanks!
