### ISSUE TITLE
posts with 5 or more pictures show inline with no padding (logged in with a pixelfed account)

### ISSUE THREAD

**Issue by wakest** [elk-zone/elk#2796]
heres what the post looks like in main.elk.zone (running [706cffe](https://github.com/elk-zone/elk/commit/706cffe209293478c84ed529fedbbd94b4d1dec0))
<img width="630" alt="image" src="https://github.com/elk-zone/elk/assets/7890201/2b202fb6-1be6-4972-ba62-af47c1864ae4">
post in question https://pixelfed.social/p/Lacalle/684124192137313050

heres what the same post looks like while logged in with a mastodon account
<img width="612" alt="image" src="https://github.com/elk-zone/elk/assets/7890201/78c7b378-c14f-4068-87cb-d3bcf705cb9e">

**Comment by shuuji3** [comment]
Thanks, I was looking for some example posts when checking #2502 yesterday.🙂  I'm going to investigate the response from Pixelfed server.

**Comment by wakest** [comment]
wow @shuuji3 you rock!
