### ISSUE TITLE
Language naming issue at Hide translation block

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2814]
In Settings > Language > At the 'Hide specific translations' block Hungarian language starts with a lowercase letter, need to replace Uppercase letter. I did not found it in the hu-HU.json file. Screenshot attachment also available. 

<img width="248" alt="Screenshot 2024-04-14 020925" src="https://github.com/elk-zone/elk/assets/11964785/dec0d5e5-79d1-405d-8103-b5f1bd49a034">

Thank you!

**Comment by userquin** [comment]
We use ISO-639-1 library, and the library has a few entries with lower case languages.

**Comment by iamdtms** [comment]
Okay then, so it's another issue.

**Comment by userquin** [comment]
no, browser Intl functions also showing `magdar`, I'll check using also country, preparing small script...

**Comment by userquin** [comment]
you can open chrome/firefox dev tools (pressing F12 key), then paste this code on console tab:
```ts
new Intl.DisplayNames(
    ['hu'],
    { type: 'language', languageDisplay: 'standard', localeMatcher: 'lookup' },
  ).of('hu')
```

and
```ts
new Intl.DisplayNames(
    ['hu-HU'],
    { type: 'language', languageDisplay: 'standard', localeMatcher: 'lookup' },
  ).of('hu-HU')
```
**Chrome**:

![imagen](https://github.com/elk-zone/elk/assets/6311119/95886b5a-67cf-4540-aa35-5b972402ed7e)

**Firefox**:

![imagen](https://github.com/elk-zone/elk/assets/6311119/b5b93af2-e1df-44dd-aaf3-89f40c8e8fef)

**Comment by shuuji3** [comment]
https://mastodon.social/settings/preferences/appearance

This is the same in Mastodon UI. I think those language names are written in each language. Although I have little knowledge of Hungarian, I guess the lowercase one ("magdar") is a formal spelling in Hungarian in terms of the language name? Wiktionary also writes "magdar" in Hungarian but "Magdar" is English spelling.

ref. https://en.wiktionary.org/wiki/Magyar

**Comment by userquin** [comment]
Here some pairs from `iso-656-1` and Intl.DisplayNames`:

![imagen](https://github.com/elk-zone/elk/assets/6311119/f369896c-79a0-41a5-a866-cc2ab8c7c96f)

![imagen](https://github.com/elk-zone/elk/assets/6311119/bb24edae-348f-43af-a307-8d295b1499e5)

**Comment by iamdtms** [comment]
magyar is a noun, but Magyarország is proper noun in English.
What confused me was that not all items capitalized.

**Comment by shuuji3** [comment]
When "magyar" is not a wrong case, I think the confusion is due to inconsistency with the above "Language" section. This capitalized one is hardcoded here:

https://github.com/elk-zone/elk/blob/c56d6b17ff50e64fb877c18adbbbe04804e81562/config/i18n.ts#L121-L125

so we should use the same case as the below ISO 639-1's ones.

![Screenshot 2024-04-14 at 20 03 03](https://github.com/elk-zone/elk/assets/1425259/73eb84cd-9584-48fc-84b6-03fdb3b101c0)

**Comment by userquin** [comment]
@shuuji3 as I mention, we use `iso-639-1` library, rn that library and Intl.DisplayNames seems to match, in Language section we're using the i18n entries (i18n.ts module in conf folder).

Maybe we can update i18n.ts module to use same lang names.

**Comment by shuuji3** [comment]
Yes, that's my understanding👍🏻  Can I try updating `i18n.ts` to use the same names?

**Comment by userquin** [comment]
I'm going to check if we can infer display names in node side (no idea if Intl in node is fine)

I'm checking some spanish "languages" like `es-419`, `ca-valencia`, `ca-ES`, `eu-ES` and `gl-ES`:

**Firefox** (seems to be fine):

![imagen](https://github.com/elk-zone/elk/assets/6311119/c94dfe64-f32f-46f1-8071-1b49b04937f3)

**Chrome** (seems to be fine, some missmatch with FF):

![imagen](https://github.com/elk-zone/elk/assets/6311119/aa92e54c-9558-4bb9-b611-e6d54204affb)

**Comment by iamdtms** [comment]
It is a style thing or it is language thing to have the first letter uppercase in lists? As a designer it is more important to have all first letter uppercase. I propose Magyar could be better in every language related list IMHO. And also important to have the same usage in every circumstances. It's only my opinion, I do not want to intervene in Elk development.

**Comment by userquin** [comment]
@iamdtms it is a problem with the language: for example, week days in Spanish are no proper names (in Spain) and so the names should be in lowercase (with some exceptions), but anyone may want to use first letter in uppercase: `monday (en) => lunes (es) => Lunes (es)` (ofc, `Lunes` is wrong)

**Comment by iamdtms** [comment]
selector:first-letter { text-transform: uppercase } also an option for proper display with no text replacement?

**Comment by userquin** [comment]
That `css` hack is wrong, not all languages using language names as proper names, in Spain `spanish` is `español` and not `Español` (in fact `conf/i18n.ts`  is wrong, we should update lang names there properly).

From `Intl` and `iso-639-1` library, the correct name seems to be `magdar` and not `Magdar` (or both are wrong, I have no idea about it)

**Comment by iamdtms** [comment]
I understand. Good luck with that multilingual thing.

**Comment by userquin** [comment]
(screenshot translation): the words used to designate the different languages are common names, which is why **they must always be written with a lower case letter**: spanish is the most studied language in the world after English.


![imagen](https://github.com/elk-zone/elk/assets/6311119/2e9b60c3-ee81-455c-a342-c83794d6974a)

**Comment by userquin** [comment]
I'm going to prepare a PR to use `Intl/ISO-639-1` language names in `config/i18n.ts`: this way Language and Translations will match.

**Comment by userquin** [comment]
@iamdtms with #2817 should be fine, languages and translations in settings language will show the same names (from `conf/i18n.ts`), we can change the names in `conf/i18n.ts` if we want

**Comment by iamdtms** [comment]
Thank you!
