### ISSUE TITLE
[Feature request] show something when there is no list

### ISSUE THREAD

**Issue by lazzzis** [elk-zone/elk#2819]
When the current user hasn't created any list yet, clicking on list button will show an empty box.

https://github.com/elk-zone/elk/assets/10359255/d3451686-7295-4280-b77b-0678507c9861

It would be perfect if we can show something here.

How about adding a 'manage list' button of navigating to `[[server]]/lists` ?

|w/o list|w/ list|
|-|-|
|<img width="315" alt="Screenshot 2024-04-14 at 2 14 50 PM" src="https://github.com/elk-zone/elk/assets/10359255/06b29ade-f152-4f23-889b-10d56d053570">|<img width="370" alt="Screenshot 2024-04-14 at 2 15 39 PM" src="https://github.com/elk-zone/elk/assets/10359255/12f3c758-765c-4535-951b-3524e414cb54">|

**Comment by shuuji3** [comment]
I think this is a good idea. I can see the similar patterns in other apps such as the playlist in a music app and bookshelf in a reading app.
