### ISSUE TITLE
Bring translate function to Elk!

### ISSUE THREAD

**Issue by alrcatraz** [elk-zone/elk#2833]
Greetings!

I'm writing this issue to recommend bringing text translate function to Elk. Since I am using Mastodon app on my cellphone, I noticed that the app contains a translate function, we just need to click "translate form XX language", the text will be translated. It is really a great function when viewing international contents, so I strongly recommend Elk to have translate function!

Hope my advice can help improve Elk!

**Comment by Shinigami92** [comment]
What's wrong with the actual implementation?

<img src="https://github.com/elk-zone/elk/assets/7195563/b2b0a651-3231-4c04-b220-cc88b414eb48" width="500px"/>

**Comment by alrcatraz** [comment]
Oh!
I'm really sorry that I suppose the function button would appear in the "more" menu, and I didn't notice that it's already there under the text...
