### ISSUE TITLE
A post editing issue

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2849]
A post editing issue: 
1. I have a post with various text and optional media & tag contents
2. I'm editing the text of it
3. I did text modifications
4. I click on save changes
5. What I see is the part of the original content, perhaps only tags of the post (?)
6. I refresh and everything seems good

**I catched it several times.** 
Can not tell more about it, some tests would also needed.

**Comment by shuuji3** [comment]
Thanks for the report. This might be a similar issue to #2255.

**Comment by shuuji3** [comment]
The above information is helpful for debugging.👍🏻  Please comment on #2255 if you find additional information.
