### ISSUE TITLE
Home feed shows posts from accounts I am not following

### ISSUE THREAD

**Issue by nileshtrivedi** [elk-zone/elk#2882]
I have been noticing this for a couple of months. My "Home" feed shows posts from accounts I have not followed:

![image](https://github.com/elk-zone/elk/assets/19304/75f3208d-c7b6-43db-9631-db92c7c90890)

**Comment by nileshtrivedi** [comment]
Actually, my server (fosstodon.org) itself seems to be doing this too:

<img width="885" alt="image" src="https://github.com/elk-zone/elk/assets/19304/625da9ae-053d-4b1d-89a2-ff4f7de1f686">

<img width="896" alt="image" src="https://github.com/elk-zone/elk/assets/19304/8322c7c9-d184-48dc-92bc-c87445594756">

Is this some big conspiracy across fediverse?

**Comment by nileshtrivedi** [comment]
Ok, never mind. I had followed a hashtag. But the user interface should have made it clear why the post is showing up in my feed.

**Comment by shuuji3** [comment]
Yes, this is a known confusing behavior. There is Issue #2636 that will mitigate this issue by adding a tag name to the header.
