### ISSUE TITLE
Embed z-index

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2926]
Having issues with notification YouTube content appearing by menu openings on device viewport.

![Screenshot_2024-08-22-18-51-38-485_com.android.chrome.jpg](https://github.com/user-attachments/assets/b3544a5a-3a64-481a-b83a-5d214e62bdd2)

**Comment by shuuji3** [comment]
Hi, thanks for the report! Which version of Elk do you currently use? We recently fixed a similar issue (https://github.com/elk-zone/elk/pull/2848) and the fixed version is available in Canary version at https://main.elk.zone

**Comment by iamdtms** [comment]
> Which version of Elk do you currently use?

v0.14.0

Probably YouTube changed something, previously never made up this kind of UI problem. Thank you.
