### ISSUE TITLE
compose panel broken on main

### ISSUE THREAD

**Issue by joelanman** [elk-zone/elk#2954]
When I press C I get this broken compose popup, pressing the Compose link in the navigation works ok

<img width="811" alt="image" src="https://github.com/user-attachments/assets/13b3e935-f834-448f-9e49-21d6cade8ea7">

Safari on Mac OS

Version
canary (dbf743a@main)
Built
11 September 2024 at 16:47:13

**Comment by userquin** [comment]
so, elk.zone have this layout, seems also broken (preparing PR):

![imagen](https://github.com/user-attachments/assets/e273befe-fc31-4b94-ae69-7df1948076a2)

this is with local change:

![imagen](https://github.com/user-attachments/assets/8c695910-cd35-4aef-bbe1-af09d3a35430)

and mobile:

![imagen](https://github.com/user-attachments/assets/0c872bde-a0cc-4996-94ae-c26ce5bdd3af)
