### ISSUE TITLE
Losing my place when clicking the tab

### ISSUE THREAD

**Issue by asmaloney** [elk-zone/elk#2972]
As of 0.15.0, it refreshes the page every time I come back to the tab, so I lose my place.

- scroll down my timeline
- switch tab to something else
- switch tab back to Elk

It refreshes, I'm at the top & I've lost my place.

Firefox 130.0.1.

**Comment by piebob** [comment]
also seeing this problem, glad to see it's already been reported. 
also ffox 130.0.1.

**Comment by asmaloney** [comment]
Wow - that's quick!

Thank you @userquin!

**Comment by userquin** [comment]
Looks like the problem still present on Firefox, using Chrome works

**Comment by jim-davenport** [comment]
I am also still seeing this issue on Firefox.

**Comment by piebob** [comment]
yeah it looks like we are still running 15.0.0 on ffox, and the commit for this fix has not been pulled in yet. this is SUPER annoying, folks--can we get a new build please? :D

**Comment by joshuaiz** [comment]
Seeing this issue in Safari as well.

**Comment by DeRuiterIndustrieleAutomatisering** [comment]
it refreshes every time when it gets the focus and becomes very, not usable, slow in Firefox. I've the same problem that when I switch to another tab the app jumps to the first post

**Comment by poopsicles** [comment]
@piebob maybe you could try using https://main.elk.zone for now, it basically follows the main branch

**Comment by userquin** [comment]
We need this PR https://github.com/elk-zone/elk/pull/2975 (still on review).

**Comment by piebob** [comment]
> @piebob maybe you could try using https://main.elk.zone for now, it basically follows the main branch

oh thank you! that is exactly what i needed.

**Comment by piebob** [comment]
oh dang, this is also still happening on main, alas.

**Comment by Cragsand** [comment]
Present on [elk.zone](https://elk.zone) v0.15.0 but not on v.0.14.0 [universeodon](https://elk.universeodon.com)

**Comment by joshuaiz** [comment]
Still happening on `main` in Safari 18.0.

**Comment by asmaloney** [comment]
It's being worked on. Patience everyone!

You can subscribe to notifications (on the right-hand-side) and you will be notified when this issue closed (i.e. the fix is merged). Then it will take some time to release & deploy.

Thanks!

**Comment by dnet890** [comment]
I use brave and it happens as well
