### ISSUE TITLE
PWA uploading media on handheld devices

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2979]
I tried to upload an image for an entry on a handheld device. Nothing happens, just a page reload, several times tried.

_I think it is an important issue. Thank you._ 

**Elk** version: **v0.15.0**

**Comment by shuuji3** [comment]
We released v0.15.1 several minutes ago and it should be available on https://elk.zone/. This version includes some fixes related to the reloading issue. Could you test if the problem still persists with the new version?

**Comment by iamdtms** [comment]
Probably https://github.com/elk-zone/elk/releases/tag/v0.15.1 solve this too. 
I will check whether fixed or not.

**Comment by iamdtms** [comment]
Works fine, thank you!
