### ISSUE TITLE
No updates received after suspending computer

### ISSUE THREAD

**Issue by palant** [elk-zone/elk#3017]
If I suspend my computer and go back to Elk afterwards, I’ll still see a push message for the notifications received in the meantime – but these notifications don’t show up in the UI. No new notifications and no new posts are being received any more, at least until I reload the page.

It seems that the WebSocket meant to receive updates is disconnected. From the look of the code, https://github.com/neet/masto.js/pull/1224 introduced automatic WebSocket reconnection as a side-effect, yet the version currently used by Elk pre-dates this change.

**Comment by palant** [comment]
Ok, I could determine that automatic reconnection is already present in the masto version used by Elk. Then it must be something else.

**Comment by palant** [comment]
So the issue is: while `masto` will re-establish the WebSocket connection if it is closed, the `subscribe` messages are not resent. As a result, quite unsurprisingly, no updates are being received.

**Comment by shuuji3** [comment]
I just merged #3019 to update masto.js to the latest version. Could you check if this fixed the WebSocket connection issue?

**Comment by palant** [comment]
Sorry about the lack of response on my part. I am in the process of giving up on Elk because of the horrible mess it makes with its client-side Markdown processing (especially when composing messages), so I have little incentive to check this before it hits a release version.

**Comment by shuuji3** [comment]
No problem! Thanks to this report, if someone encounters the same issue in the future, we can easily resume the investigation.
