### ISSUE TITLE
Profile avatar image does not respect reduced motion setting

### ISSUE THREAD

**Issue by shuuji3** [elk-zone/elk#3044]
When reduced motion setting is enabled, the avatar image with animation should be stopped but it has a movement now.

example: https://main.elk.zone/mastodon.social/@radiojammor@mastodon.scot

![Image](https://github.com/user-attachments/assets/53cdfc53-67d0-48bb-bb36-fd8b3d32cdb4)

**Comment by AndrewCrescencio** [comment]
hi, I'll help
