### ISSUE TITLE
missing info boxes in profile and pinned posts

### ISSUE THREAD

**Issue by Andre601** [elk-zone/elk#305]
Checking my own profile, it seems like a few things are inconsistent between elk and a Mastodon web-client.

Namely, I found the following:

- [ ] Some info boxes (Actually all except one) are missing.
- [ ] Pinned posts are not displayed.

Profile on Elk:
![grafik](https://user-images.githubusercontent.com/11576465/205358584-15445bf4-dd10-44f3-99be-43f9e08e676f.png)

Profile on Mastodon:
![grafik](https://user-images.githubusercontent.com/11576465/205358627-370087c3-db2e-46bc-9a4f-0d64c2fd4259.png)

**Comment by forestsystem** [comment]
I noticed this too! It would be nice to be able to see people's pinned posts when going to their profiles.

**Comment by astrowonk** [comment]
Yes +1 for supporting pinned posts and showing so UI to show if links are verified or not.

**Comment by shaunagm** [comment]
Just tried to view someone else's pinned posts in Elk and was startled to realize I couldn't. Would love to have this - it's a pain (though of course always an option) to have to open up the user's profile in some alternative frontend that supports pinned posts.

**Comment by sloanlance** [comment]
@elk-zone: @shuuji3 has opened PR #2779.  It looks good and I've tested it.  Why not approve and merge it?

Many accounts use pinned posts to give introductions about themselves or their content.  By Elk not displaying these pinned at the top of their post timelines (as the account owners expected when they used the "pin" option) those pins are hidden down in the timeline, appearing around the time they were posted.  That is not how the official Mastodon clients work.  By working this way, Elk breaks the Principle Of Least Astonishment ([POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)).
