### ISSUE TITLE
Cannot re-authenticate main.elk.zone to Mastodon

### ISSUE THREAD

**Issue by johnsonm** [elk-zone/elk#3072]
A few days ago (26 November), I found that my main.elk.zone Chrome PMA on my Android 15 phone was no longer authorized. Trying to sign in took me to the sign-in page on my instance, where I authorized elk and was redirected back. I tested from directly within chrome and saw the same problem. I got a 500 from main.elk.zone, and the new oauth application was never used. Every time I try the auth flow it creates a new application, and each time I get the 500 from main.elk.zone. I've tried this intermittently until moments before filing this isue.

However, I can successfully log in on elk.zone, so the bug appears to be in main but not yet on stable.

This isn't obviously (to me) the same as #2279

You should find 500s in your logs from 70.229.193.23 for some of these attempts in the past hour.

**Comment by win98se** [comment]
#3056
The same problem also happens on Microsoft Edge for Windows.

**Comment by johnsonm** [comment]
Missed that on my search, I'll close duplicate, thanks!

**Comment by johnsonm** [comment]
Oh, that wasn't an issue, that's why it didn't show up on my search. We should have an issue for this.

**Comment by shuuji3** [comment]
We also confirmed the issue and are investigating the cause. It looks like this issue happens on the server side (specifically around `/signin/callback` endpoint), not just on a specific browser or OS.
