### ISSUE TITLE
Markdown list: bad rendering

### ISSUE THREAD

**Issue by kazukyakayashi** [elk-zone/elk#3114]
Markdown list rendering has a problem

My Hollo account on Elk (elk.zone) with Hollo message

![Image](https://github.com/user-attachments/assets/b88c79f0-248e-4d3d-9ac2-7d0e3cda5670)

**Comment by shuuji3** [comment]
Hi @kazukyakayashi, thanks for reporting the issue! We recently fixed a similar problem at https://github.com/elk-zone/elk/pull/3039. Could you try the Canary version of Elk, available at https://main.elk.zone?

**Comment by kazukyakayashi** [comment]
Indeed the problem is solved on https://main.elk.zone/ 👍 

![Image](https://github.com/user-attachments/assets/c82cacd6-5fc1-495f-ab46-f292bbb6698f)

**Comment by shuuji3** [comment]
Great:+1: There's no fixed timeline yet but this fix will be included in the next update. Please use Canary version meantime.
