### ISSUE TITLE
Embedded videos from Streaming services

### ISSUE THREAD

**Issue by ayoayco** [elk-zone/elk#356]
If the PreviewCard.type is `video` and PreviewCard.html contains  an iframe, we can embed the video in the StatusCard or StatusDetail and be able to watch on Elk. 

For video preview, There's a case when the width and height property does not match the image
    - this has a square image: https://elk.zone/fosstodon.org/@polarfront@snabelen.no/109474214556574293
    - but we're getting `width: 350` and `height: 467`
    - I think because this is a `type: video` and the `width` and `height` properties might be describing the iframe instead of the image

We can go for two overlay buttons: one to play video on Elk and other links to the source:

<img width="759" alt="Screenshot 2022-12-07 at 2 22 41 PM" src="https://user-images.githubusercontent.com/4262489/206197244-4df5b635-769b-4d48-bf5a-6d152360af3e.png">

YouTube is giving an example.

```
{
    "url": "https://www.youtube.com/watch?v=-R0UYHS8A_A",
    "title": "Afternoon Jazz 🎷 [lofi hip hop/study beats]",
    "description": "",
    "type": "video",
    "author_name": "Lofi Girl",
    "author_url": "https://www.youtube.com/@LofiGirl",
    "provider_name": "YouTube",
    "provider_url": "https://www.youtube.com/",
    "html": "<iframe width=\"200\" height=\"113\" src=\"https://www.youtube.com/embed/-R0UYHS8A_A?feature=oembed\" frameborder=\"0\" allowfullscreen=\"\" title=\"Afternoon Jazz 🎷 [lofi hip hop/study beats]\"></iframe>",
    "width": 200,
    "height": 113,
    "image": "https://cdn.fosstodon.org/cache/preview_cards/images/012/574/228/original/1afec34c903be880.jpg",
    "embed_url": "",
    "blurhash": "UAB.7RnhNHJAxtoeoIR-0~NcxYR+EMENs:xY"
}
```

## Screenshots (current preview w/o embed)

![Screenshot 2022-12-06 at 4 55 50 PM](https://user-images.githubusercontent.com/4262489/205960297-0489248f-e100-49a8-b433-18e6a5e18fb2.png)

**Comment by aeharding** [comment]
Hi there! 

Here is an example PeerTube video link for testing (paste this into your Mastodon search bar to go to the post): https://urbanists.video/w/pc1LWry9c5Nxda1147ZTLK

And here is some additional context into how Mastodon handles this:

Mastodon inserts `card.html` into the DOM. Mastodon injects autoplay parameters onto the iframe URL in order to avoid needing to click play twice (once on the card, once on the iframe video) with [`addAutoPlay()`](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/features/status/components/card.js#L40).

Mastodon's embedded video logic [can be found here](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/features/status/components/card.js#L169).

**Comment by jeffsikes** [comment]
Hi! I just so happened to have done some research into Preview Cards recently, so thought I'd [share that post here](https://box464.com/posts/mastodon-preview-cards/)

Happy to offer any insight or testing assistance needed for this one. You may want to check out the [@timeline_tester](https://botsin.space/@timeline_tester) account I created to run my own tests, and you can check for the [ExternalVideo](https://botsin.space/@timeline_tester/tagged/ExternalVideo) tag if you're focused on video specifically. 

There's all kinds of content that has the potential for being added here, especially excited for sites like [Stitcher](https://botsin.space/@timeline_tester/110209129064555570) for podcasts and [SoundCloud](https://botsin.space/@timeline_tester/110197332849543173), [FunkWhale](https://botsin.space/@timeline_tester/110177907066556119) for audio (support your Fediverse cousins!).

I've also started [a list of sites that return status.post.html content](https://docs.google.com/spreadsheets/d/1PAxGxFIWEKf8KCOXE1J1B3WrQh8L9TX4KalDvphYAwU/edit?usp=sharing), but I'm not very far along yet. Hoping to get some[ outside assistance gathering and testing them](https://docs.google.com/forms/d/e/1FAIpQLSd4jY8gdmdMCcVgFvl3HzDizwfA7yF1Myl8vbiGEJ1QDp-qNQ/viewform). If you read my post - it's not clear cut which links are going to give you that nice oEmbed link and which one's aren't.

Looking forward to seeing how Elk handles this! It's one of the more complex issues I've come across so far in regards to Mastodon timelines.
