### ISSUE TITLE
Profile banner should start at the top of the page

### ISSUE THREAD

**Issue by patak-dev** [elk-zone/elk#36]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/583075/203749978-51f75284-ce5f-4b67-b787-b74d2c2d8131.png">

The back navbar could be transparent (only having a solid background for the button) until the user starts scrolling down, so the banner starts right away at the top.

**Comment by webfansplz** [comment]
Now that it's working well, we can close it.
