### ISSUE TITLE
Mixed profile data between profiles 

### ISSUE THREAD

**Issue by patak-cat** [elk-zone/elk#366]
Reported by @wakest
> just logged into two accounts and switched from one to the other: and now its showing the wrong profile data attached to a different user profile. this is a bad bug that shouldn't be possible...

![image](https://user-images.githubusercontent.com/583075/206304202-5635d781-05e5-499a-8fef-b0d49da503df.png)

**Comment by wakest** [comment]
this is marked as fixed but I seem to still be having this issue. 

the account @twilight@autonomous.zone is logged but being looked at from another account that is logged in, @wakest@mastodon.social.  its showing a post I have no recollection of ever seeing and that was not boosted by that account ever. also the server that is logged into: mastodon.social: has a history of posts already on display from this account
![image](https://user-images.githubusercontent.com/7890201/212488714-1838daee-f3c2-42fc-b59b-82de8259845d.png)
