### ISSUE TITLE
Default to webtoo.ls, and local instead of federated

### ISSUE THREAD

**Issue by patak-cat** [elk-zone/elk#385]
https://mas.to -> redirects to https://mas.to/explore

IMO, we should switch to webtoo.ls by default, but redirecting the local timeline is a better default to me compared to explore.

There seem to be also some issues with routes redirects from the server's root:

https://elk.zone/mas.to -> Not Found, should redirect to https://elk.zone/mas.to/public/local
https://elk.zone/mas.to/ -> same

**Comment by randulo** [comment]
It is my belief that Elk presents a "prettier face" to first-time potential Mastodon registrants. It follows in my mind, that looking at that login page, a register button be added. I did not know there was an instance (we should say server to the public) associated. If that instance was the one they would be automatically registered on, and if this is thought to be a problem, the registration could be temporary until the user finds the most appropriate instance. Getting them on board, letting them play around and try engaging with locals and finding people to follow, would do wonders for acceptance. There's nothing worse than walking into a room full of people who know each other and are amicably chatting away. Looking at a local feed that is accepting people to join in would be game-changing for Mastodon use. After people get into Mastodon with or without Elk, they will be exposed to the rest of the fediverse in a much friendlier way.
