### ISSUE TITLE
navigating to profile through address bar with https:// results in inconsistent behavior 

### ISSUE THREAD

**Issue by wakest** [elk-zone/elk#437]
navigating to https://elk.zone/https://girldick.gay/@anna gives:
Error
Something went wrong
Invalid Version: 4.0.2+cat+1.0.12+nya-1.1.9

but navigating to https://elk.zone/girldick.gay/@anna (without https://) redirects to https://elk.zone/social.wake.st/@anna@girldick.gay and loads correctly

**Comment by boehs** [comment]
Can no longer reproduce
