### ISSUE TITLE
UI elements to help understand threads

### ISSUE THREAD

**Issue by patak-cat** [elk-zone/elk#47]
UI in Twitter with a line showing the connection between messages
![image](https://user-images.githubusercontent.com/583075/203811771-77df29b7-f9bb-4ae3-a5c8-40285afcbfcd.png)

An example from another [mastodon client](https://mas.to/@ayo@fosstodon.org/109341743160486404)

**Comment by ronilaukkarinen** [comment]
On the home feed I'm not seeing the original post? Halcyon has this but on Elk it's not implemented? @patak-dev

**Comment by patak-dev** [comment]
Would you give more context? What original post? Do you mean quote posts?

**Comment by ronilaukkarinen** [comment]
> Would you give more context? What original post? Do you mean quote posts?

Screenshot from [Halcyon](https://halcyon.cybre.space/):

<img width="590" alt="Screen-Shot-2023-01-30-09-15-51 78" src="https://user-images.githubusercontent.com/1534150/215411659-f4685759-9e54-42aa-9910-f484a609ca12.png">

This kind of threading (with all replies) would be fun to see on Elk. I presumed this PR was this but it seems not present on Elk. If I misunderstood, we should open another request/issue about this.

**Comment by patak-dev** [comment]
I still dont understand the feature. That looks very similar to our connected replies in Elk. What is Elk missing from that screenshot?

**Comment by ronilaukkarinen** [comment]
> I still dont understand the feature. That looks very similar to our connected replies in Elk. What is Elk missing from that screenshot?

It seems it's not consistent. All threads should be fully shown - at least that would be the Halcyon's feature that I like very much!

Right now on home feed:

![Screen-Shot-2023-01-30-14-53-50](https://user-images.githubusercontent.com/1534150/215483465-7b78f733-fd14-40bb-a6da-77ed1a77993e.png)

Then again, some shown as this, which is exactly what I mean but it seems it's not consistent?

![Screen-Shot-2023-01-30-14-54-31](https://user-images.githubusercontent.com/1534150/215483569-70dfae70-51bb-4c38-8998-785599071363.png)

Most of the replies show even the line but then it just cuts it short:

![Screen-Shot-2023-01-30-14-56-10](https://user-images.githubusercontent.com/1534150/215483777-f08010f0-318a-4ee0-a75a-5f34a4466585.png)
