### ISSUE TITLE
how to write long status?

### ISSUE THREAD

**Issue by severak** [elk-zone/elk#472]
When I am writing longer status (being it for Fedi or Facebook) I sometimes write it in text editor and then copy and paste it into window of that social network. I tried this today with Elk and it seems that long statuses are not yet supported.

When I pasted my 1784-character-long status, it was simply not possible to paste it into Elk. No error message no nothing. Both Pinafore and official Mastodon frontend let me paste it but display how many characters I need to remove to fit in my status length quota.

I think this would OK enough for Elk but I wish we can go step ahead and make some tool which would helping with transforming long statuses into threads.

**Comment by boehs** [comment]
You can now paste in as much content as you want and edit it down

**Comment by peterbud** [comment]
> You can now paste in as much content as you want and edit it down

I guess this issue can then be closed?
