### ISSUE TITLE
Caret appears in wrong place when continuing a reply

### ISSUE THREAD

**Issue by TodePond** [elk-zone/elk#488]
Steps to reproduce:
1. Click the reply button on a post.
2. Click out of the reply window to leave the editor.
3. Click on the reply button again.

Expected:
The text caret should be after the recipient's handle.
![image](https://user-images.githubusercontent.com/15892272/208897401-27443113-3866-4680-9f33-1ca1d16a9652.png)

Actual:
The text caret is before the recipient's handle.
![image](https://user-images.githubusercontent.com/15892272/208897475-f7c9469e-bc24-40b5-8517-9310d0b5ef35.png)

**Comment by webfansplz** [comment]
The issue seems to have been fixed and we can close it.
