### ISSUE TITLE
Make dark mode toggle more obvious | Use preferred dark mode

### ISSUE THREAD

**Issue by Shinigami92** [elk-zone/elk#56]
I literally searched the dark mode toggle everywhere at first.
In my profile settings by clicking on my profile below the compose button or in the lower right corner.

It took me around 10 seconds to find it in the right lower corner.

---

I'm also not sure but does it use already preferred color schema by default? It was light mode for me by default.

**Comment by boehs** [comment]
I'm going to close this according to @danielroe 's comment and the fact there is now an option for it in the settings
