### ISSUE TITLE
pwa: Drag down to refresh shouldn't reload all posts

### ISSUE THREAD

**Issue by TodePond** [elk-zone/elk#600]
When I drag down on the PWA, currently: All posts get wiped away and reloaded. This feels clunky too me.

Ideally, I would like to be able to keep all of the other posts there, and just load in any new ones.

Is this do-able within the PWA? or not?

https://user-images.githubusercontent.com/15892272/209807479-b4b9633b-821a-48f0-9002-a72ccc00a7e9.mp4

**Comment by Moshyfawn** [comment]
Would it make sense to close it in favour of #94?

**Comment by TodePond** [comment]
Yes I think so :)
