### ISSUE TITLE
Mobile (Android, PWA): login hostname auto-complete hides sign-in button

### ISSUE THREAD

**Issue by snail-coupe** [elk-zone/elk#670]
I'm not sure how much of this is my browser being helpful .. (Edge 108, Android 12)

On the initial "Choose Server" stage of the login in using a private server which doesn't appear in the auto-complete list. 

![Screenshot_2022-12-31-12-17-07-015-edit_com microsoft emmx](https://user-images.githubusercontent.com/53581981/210136791-b63f84e7-97d6-496e-9799-d292eaebde0d.jpg)

Unfortunately that means the list obscures most of the sign-in button.

I've seen similar issues with auto-complete in the browser but normally tapping outside of the dialog makes the list disappear but it didn't in this case.

Hitting the enter key just replaced what I'd written with the first entry in the list.

**Comment by webfansplz** [comment]
The issue seems to have been fixed and we can close it.
