### ISSUE TITLE
PWA and iOS - it gets suspended and doesn't reload new statuses after relaunch

### ISSUE THREAD

**Issue by draga79** [elk-zone/elk#750]
iOS suspends PWAs after 10 minutes of idle (minimised) time. At relaunch, Elk doesn't seem to understand it's been "resumed" and the timeline is stuck in an old state. The only way to refresh is to kill the app and relaunch, but it's not that comfortable.
Thank you!

**Comment by ushuz** [comment]
Currently, clicking Elk logo will force a refresh/reload. But unfortunately Elk logo is not visible on smaller screens. Maybe we could extend that click-to-refresh function to Home timeline title as well?

**Comment by johnsonm** [comment]
Alternatively, #94 would make sense. My default behavior for an app on mobile is to try pull-to-refresh, and I keep trying it on Elk as PWA (on Firefox on Android in my case).

**Comment by johnsonm** [comment]
My current workaround is to turn the phone into landscape orientation, click the Elk logo, then turn the phone back into portrait orientation.

**Comment by johnsonm** [comment]
Mentioning this workaround was apparently cursed, as clicking the Elk logo is no longer refreshing at least on the PWA.
