### ISSUE TITLE
Reply editor should compress like the home page editor

### ISSUE THREAD

**Issue by TodePond** [elk-zone/elk#759]
The reply editor is large, and it feels like it's in the way when sending a reply.

![image](https://user-images.githubusercontent.com/15892272/210536919-8a87129b-4e7c-4d8c-8559-3164e9838a19.png)

I think that it should compress in a similar way to the home page editor:
![image](https://user-images.githubusercontent.com/15892272/210537149-c1017a76-1d77-4222-8153-e5fde570ce3a.png)

**Comment by boehs** [comment]
Implemented at some point
