### ISSUE TITLE
Characters appearing wrong in browser tab

### ISSUE THREAD

**Issue by TodePond** [elk-zone/elk#773]
This post appears like this in the browser tab

![image](https://user-images.githubusercontent.com/15892272/210576865-aface9d5-0aa3-42f3-bf84-d6e7adc41a18.png)

![image](https://user-images.githubusercontent.com/15892272/210576930-7db88e10-11cf-4941-994d-930076884b63.png)

**Comment by boehs** [comment]
Can't repro
