### ISSUE TITLE
feat: Support polls in posts

### ISSUE THREAD

**Issue by wheatjs** [elk-zone/elk#81]
When creating a post we should be able to add polls to the post. I'll be happy to take up this task. We can probably use a UI similar to Twitter's. The only difference seems to be that Mastodon allows you to toggle between single and multi poll responses.

**Comment by djwfyi** [comment]
Can we revisit this?
[PR 210](feat: polls #210)https://github.com/elk-zone/elk/pull/210) adds the ability to display and interact with polls, but we still do not have the ability to create polls while composing a post. I have to go to other front ends to do so.
Is creating polls in the post composer in the roadmap somewhere?

**Comment by patak-dev** [comment]
@djwfyi I created a new issue to track poll creation here:
- https://github.com/elk-zone/elk/issues/1769
