### ISSUE TITLE
feature-flags causing an "undefined is not an object" error

### ISSUE THREAD

**Issue by osmaa** [elk-zone/elk#825]
version 0.1.18 on elk.zone, running on Safari (Mac OS Monterey 12.6)

It appears there experimental feature flags code has some unstable paths. I'm not sure how I ran into this the first time, but exploring a number of ways to try to reproduce the issue, this appears reliable

steps to reproduce:

0. open dev console
1. log out of Elk and delete local storage content (this is critical, you have to start from clean slate)
2. reload elk.zone
3. observe that local storage for elk.zone contains elk-feature-flags object for anonymous
3. log in (in my case, on mas.to)
4. observe that local storage for elk.zone continues to contain elk-feature-flags object for anonymous, not for logged in user
5. observe console error messages:

```
[Error] TypeError: undefined is not an object (evaluating 'W().experimentalGitHubCards')
(anonymous function) — StatusPreviewCard.vue_vue_type_script_setup_true_lang.5351018d.js:1:6445
(anonymous function) — entry.f141db90.js:9:23765
Cn — entry.f141db90.js:1:13258
Et — entry.f141db90.js:1:13338
run — entry.f141db90.js:1:4739
Ll — entry.f141db90.js:1:23276
Lx — entry.f141db90.js:9:23750
setup — StatusPreviewCard.vue_vue_type_script_setup_true_lang.5351018d.js:1:6437
[snip]
```

**Comment by tom-sherman** [comment]
This could also be related to #1013 and #1068

**Comment by osmaa** [comment]
Meta question: I have not seen the error since 0.2.0, do you wish me to close the issue or is that part of release management?

**Comment by patak-dev** [comment]
Yes, next time you can directly close it 👍🏼 
We can always reopen it or create a new one if we see this happening again. Great to hear that this is no longer happening
