### ISSUE TITLE
bug: Back button exits website on desktop

### ISSUE THREAD

**Issue by jahands** [elk-zone/elk#866]
While browsing on Desktop (Edge), I was confused by this new arrow:
![image](https://user-images.githubusercontent.com/10719325/211179229-ee22d4e5-e69d-4a52-ac10-a11da18b24d3.png)

When I first clicked it from the Home tab, it exited the website. After going back, I figured out that it's a back button, and works fine when you don't click it when first opening Elk.

I'm guessing the way it works is it goes back one page in the history.
We could probably fix this by making it go to `/home` if the previous history item is not on the Elk website (or disable it.)

**Comment by webfansplz** [comment]
Fixed in #958 .
