### ISSUE TITLE
Editor replaces character instead of inserting it

### ISSUE THREAD

**Issue by cyberalien** [elk-zone/elk#924]
When typing text before emoji, editor replaces emoji instead of adding text.

Steps to reproduce:
1. Type any text + emoji. Example: `Test🐱`
2. Press left key
3. Type any letter

Instead of inserting a letter before emoji, editor replaces emoji.

Could be related to this issue: https://github.com/elk-zone/elk/issues/921

**Comment by boehs** [comment]
Can't reproduce.
