### ISSUE TITLE
Let opt-out usage of inclusive syntax

### ISSUE THREAD

**Issue by edimitchel** [elk-zone/elk#952]
Exclusive to french (based on what I know), I know lot of people doesn't like the usage of dot-syntax in french.
For several reasons: not officially supported by the French Academia, heavy to read and make sentence longer.

So, as Twitter doesn't practice dot-syntax, we could in a sense follow to encourage more the migration and not force to use that syntax.
Also, I know Mastodon instances is using intensively that syntax.

I purpose to add a new wellness option, or a separated language (french without dot-syntax), or an option only for language which could have dot-syntax like difference.

**Comment by edimitchel** [comment]
I can understand your position and I agree.
However, I would like to add that the French dot-syntax is not welcomed to everyone, by default we would enable this syntax, and we won't encourage to disable it. For UX purpose, a few people could prefer to have lighter text without that syntax (without taking attention to the masculine form).
That's why I suggest to let this option as an opt-out option because by default we encourage people to use it.
The day the French academia is officially publish the French inclusive notation, yes, we could remove that because it will be globalized to anyone, not only to people praticing it daily.

**Comment by Ember-ruby** [comment]
this just seems like more work just to be less inclusive, which is, er, *not great*

i get your position, but languages aren't governed by an org, do english speaking people only use language that's in (e.g) the oxford dictionary? no. as that's not how language works.

**Comment by patak-dev** [comment]
There were some discussions in Discord and in other issues here that we should take into account. While I agree that using inclusive language is better, we need to see how this affects screen readers and a11y in general. Yesterday I discussed with someone that pointed out that some folks (on the Austistic spectrum for example) had real issues parsing the text when characters like `.` or `@` where used. I think it would be good to get the opinion of some experts on this matter to see what is the best default on the a11y while also promoting a well-intended switch in the way we use our languages.

**Comment by kerunix** [comment]
I completely agree that this can affect screen readers and a11y in general. I found a few ressources (mostly in french since this is a french only issue as far as I know) that give other options to have a better and more inclusive use of the language while maintaining good a11y and screen readers compatibility. Most of those resources recommend that the way we write our text takes into account both genders.

When it comes to nouns, instead of using "développeurs" (masculine for developer), the dot syntax recommends using "développeur·euses" which is more inclusive but less supported by screen readers and can also make the text less readable for folks with dyslexia or on the autistic spectrum. The recommended way then becomes "développeurs et développeuses", which is both more inclusive AND supported by screen readers.

When it comes to pronouns, the neutral pronouns "iel" (singular) and "iels" (plural) appear to be well supported by screen readers and are in use on the french version of Twitter.

I'd say the best way to approach this to stay inclusive while preserving good a11y would be to update our i18n strings based on those recommendations rather than maintaining multiple sets of i18n files.

**Comment by rtxanson** [comment]
I recently became aware of a more flexible translation system that could help: https://projectfluent.org/, there is also a [vue library](https://github.com/fluent-vue/fluent-vue) for it, and the .ftl file format is supported in Pontoon. Reasonably one could structure language rules to support user-selected language options, without cluttering up locales with variant files.

**Comment by ZMYaro** [comment]
> languages aren't governed by an org

@Ember-ruby Before edimitchel calls it out: French is an odd case where there _is_ an entity that is recognized as THE authority on the French language (the French Academy edimitchel referred to), however I agree with your position that we can and should use syntax that has not yet been officially approved when the official syntax is not inclusive.

**Comment by michelc** [comment]
Perhaps at first, to facilitate the adoption of Mastodon and Elk it's easier and more comfortable to not insist too much on inclusive writing.

We could start quietly with neutral words ("compte" rather than "utilisateur" for example, as it has been done on WordPress (https://fr.wordpress.org/2020/11/26/wordpress-5-6-des-changements-visant-a-ameliorer-linclusivite-de-linterface-dadministration/).

I'm not familiar enough with Vue... but if it's not too complicated to have an option to activate or not the inclusive writing, it's indeed a good idea.

I think it's better to have the "traditional" spelling by default and that it's a voluntary option to activate it, in order to avoid friction.

On the other hand, we shouldn't hesitate to use directly what Twitter already uses like "iel" for example.

**Comment by edimitchel** [comment]
My issue is not about making inclusive writing as a bad way! I'm thinking about people not used to read this way of writing, especially for Twitter users. Also, forcing using it it probably not as inclusive, we should (if not too complicated) to include people who don't like this syntax.

About your opinion @michelc, I'm not totally agreeing. We should make the inclusive syntax by default but let the user disabling the inclusive syntax for the language which supporting it.

About neutrals words, it's a good idea when choice doesn't sounds odd. `Compte` instead of `utilisateur` sound good for me.

**Comment by ZMYaro** [comment]
@michelc Decisions we make affect who will adopt Mastodon and Elk.  Intentionally preferring inclusive language can facilitate adoption by people who prefer inclusive language; intentionally preferring less inclusive language can facilitate adoption by people who do not.

**Comment by ZMYaro** [comment]
Additionally, if we are agreed that we would want to move toward inclusive language sooner or later, I would say better to keep it inclusive now than face potential opposition to a change down the road.

**Comment by edimitchel** [comment]
We should let people choose for that, it's a division subject I guess.
Let them choose, but encourage by default to adopt inclusive syntax.

**Comment by michelc** [comment]
There are a lot of difficulties when you come from Twitter. And this should not be an additional difficulty to switch to Mastodon.

But since Elk already makes this transition quite easy, it should be fine :)

**Comment by ZMYaro** [comment]
@fenarinarsa Do you have a link to the Mastodon PR?

**Comment by fenarinarsa** [comment]
Translations for Mastodon are submitted through Crowdin and selected with a vote system. So my contributions and votes cannot be linked directly.

https://crowdin.com/project/mastodon/fr

**Comment by edimitchel** [comment]
As we have now variant languages, we can without complexity support different version of language.
For Quebec also.

So what I suggest is to provide the french language with inclusive or neutral vocabulary (as for now), and add a variant for the legacy french syntax.
We should be inclusive yes, but also, inclusive for people who prefer simple interface without taking care to the form of word but the background meaning, I think it's necessary.

**Comment by fenarinarsa** [comment]
> So what I suggest is to provide the french language with inclusive or neutral vocabulary (as for now), and add a variant for the legacy french syntax. We should be inclusive yes, but also, inclusive for people who prefer simple interface without taking care to the form of word but the background meaning, I think it's necessary.

Honestly I also agree with that. There's even some cases where the current translation is not correct (like "abonné⋅e⋅s" for "mutuals"), but making a more precise translation with inclusive vocabulary will make it heavier ("mutuels" => "mutuel⋅le⋅s").
This definitively can be a French variant like French and Canadian French often are.

That said I won't make another PR, you got my suggestions, it can be modified afterwards but the more time is spent, the less the PR is relevant and becomes harder to merge with main.

**Comment by ZMYaro** [comment]
> We should be inclusive yes, but also, inclusive for people who prefer simple interface without taking care to the form of word but the background meaning, I think it's necessary.
Not to go into a whole spiel about the [paradox of tolerance](https://en.wikipedia.org/wiki/Paradox_of_tolerance), but please do not equate being inclusive of all genders to being inclusive of people who prefer less inclusive language.

**Comment by edimitchel** [comment]
> Not to go into a whole spiel about the [paradox of tolerance](https://en.wikipedia.org/wiki/Paradox_of_tolerance), but please do not equate being inclusive of all genders to being inclusive of people who prefer less inclusive language.

Sorry, I mean including people who just don't care about the form but want the meaning to have better UX.
I think even for used inclusive texts people will prefer simpler UI and have focus on content which could be freely writing with or without inclusive form.
Just, not force people, let them choose, freedom is key. That's it :)

**Comment by Siphonay** [comment]
The only people that inclusive language makes software "harder to use" for are people who have a problem with women being included in language by default and/or non-binary people being allowed to exist in the language at all.

Pardon my lack of precious _universalism_ but as a French non-binary person, I believe that people who oppose my rights (materially, no matter their stated or genuine intentions) should certainly not be catered to by having an option to make it easier for them to ignore my existence no matter their concern-trolling. And I don’t think it’s a fundamental freedom to let people have either.

I agree with @ZMYaro on pretty much everything xe said here but I want to comment on this:
> French is an odd case where there is an entity that is recognized as THE authority on the French language

The Académie is only recognized by the French government (and even then), but France is not the only Francophone country in the world, and I can guarantee you that the vast majority of French people, even those who do not have a negative opinion of it, are really not keeping up with all their communiqués (which are sometimes wrong or contradictory) about how language should be used. That, and they’re not an apolitical force and [have been and are still serving reactionary and oppressive ideologies](https://www.youtube.com/watch?v=hfUsGmcr1PI).

**Comment by edimitchel** [comment]
As we receive a lot of feedback there, I'll close this discussion and conclude this feature request is not welcomed.
Thank you for all your feedback and opinions.

I hope my feature request doesn't hurt anyone, and again, I didn't want to suggest any non-inclusive action to anyone.
See you there.

NB: #1434 solved partially the inclusive syntax by using neutral word, so, in a sense, if we could adopt neutral which doesn't reduce readability, go for it.
