### ISSUE TITLE
Add discord-style emoji autocomplete

### ISSUE THREAD

**Issue by piotrski** [elk-zone/elk#968]
Typing `:` should open emoji autocomplete list just like in discord/slack

**Comment by tom-sherman** [comment]
Also the first party mastodon web client already has this.

**Comment by ahonn** [comment]
Maybe I can implement this feature, and it seems that just do it the way Mention/Hashtag does

**Comment by ahonn** [comment]
> https://github.com/elk-zone/elk/issues/1077 contains some good thoughts on UX here.

Implemented a diacord-style emoji suggestion on this PR：https://github.com/elk-zone/elk/pull/1066
