### ISSUE TITLE
Multiline code format doesn't show first line

### ISSUE THREAD

**Issue by funkycode** [elk-zone/elk#986]
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

There is multiline code format used when wrapping with ``` -> will use {wrap} to avoid github to wrap it
Seems like if I have text on first line where symbols are used - this text is not displayed

So, 
{wrap}foo
bar{wrap}

will end up only having "bar" in code snippet

### Reproduction video or screenshot

![image](https://user-images.githubusercontent.com/594204/212037286-293fb24c-94ae-4cac-bbfb-664f8b387fd0.png)
![image](https://user-images.githubusercontent.com/594204/212037835-a4a0f720-5aa9-407c-b073-6d2ff25ce1ee.png)

**Comment by cyberalien** [comment]
That's correct Markdown behaviour. You need new line after ```, otherwise `foo` is treated as highlight syntax.

Try posting same stuff here to see what I mean:
```foo
bar```

**Comment by cyberalien** [comment]
Actually, there is a bug. Last line should not have been treated as code closing because it contains text. ``` should be on its own line.

**Comment by ayoayco** [comment]
```foo
bar```
`foo`

**Comment by ayoayco** [comment]
Closing this for now as there needs to be a new line after the opening in multi line wrapper
