### ISSUE TITLE
Back button after openning a post

### ISSUE THREAD

**Issue by haunt98** [elk-zone/elk#991]
### Clear and concise description of the problem

It's nice to have back button to indicate back after openning a post.

elk:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/5424272/212046826-d582f5e2-6100-4f6b-8b3c-d1c48080efa8.png">

Twitter:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/5424272/212046939-5c74d3ae-9799-4824-b7e3-a31fb0bc6d3c.png">

### Suggested solution

Add back button

**Comment by ayoayco** [comment]
Closing this now as we are showing a back button on canary version 
<img width="718" alt="Screenshot 2023-01-31 at 7 24 45 PM" src="https://user-images.githubusercontent.com/4262489/215849490-a0c8d76b-07ac-499e-9011-74ce194b0059.png">
