### ISSUE TITLE
Support push notifications for multiple instances at once

### ISSUE THREAD

**Issue by wryk** [elk-zone/elk#999]
### Clear and concise description of the problem

I can't enable push notification on multiple accounts.

Currently clicking "Enable push notifications" button in the settings works fine the first time but doesn't anymore when trying with another connected account (do nothing, doesn't raise an error or trigger a request).
Moreover if I enable push notifications and then disable them for account A I still can't enable them for another account, **even if I sign out of account A**.

### Suggested solution

ServiceWorker's PushManager can only have one subscription but according discussion for a [similar request on pinafore client](https://github.com/nolanlawson/pinafore/issues/1274#issuecomment-508946687) this should be doable without external services.

### Additional context

If this is not possible with current browser APIs the UI should reflect this limitation better than a no op button.

**Comment by userquin** [comment]
@wryk push notifications are per server, you must enable/disable per server: you can do it signing out or removing subscription from Settings > Notifications > Push Notifications

**Comment by wryk** [comment]
@userquin Maybe I'm not understanding right "per-server account" but I don't have the behavior you are describing. I can't enable more than one subscription and this is the only one I can disable/enable after that. Disabling push notifications or signing off do nothing about it.

In this recording of the current behavior accounts are from different servers.
[output.webm](https://user-images.githubusercontent.com/1964408/212110545-0ce874b7-bf67-4c72-b87e-c2e26444f610.webm)

**Comment by userquin** [comment]
@wryk it seems we have a problem, I'll check it later...

**Comment by userquin** [comment]
@wryk browsers seems to not support multiple push subscriptions

![imagen](https://user-images.githubusercontent.com/6311119/212301723-ca8c1673-0bf7-4ebc-93d3-a5f1c81d5927.png)

**Comment by userquin** [comment]
pinafore suggestions cannot be done (https://github.com/nolanlawson/pinafore/issues/1274#issuecomment-508946687), we've distinct vapid_keys per backend and we cannot reuse the vapid_key from one backend in another one; the backend will connect to browser backend relay to send notifications back to the client, we're sending keys from one server to another one, we're moving the error from client to backend

We'll need to add a push notifications proxy, a lot of work.
